const links = {
  bamSciFi:"https://www.bam.org/film/2026/arthouse-scifi",
  memoria:"https://www.bam.org/film/2026/arthouse-scifi-memoria",
  stalker:"https://www.bam.org/film/2026/arthouse-scifi-stalker",
  solaris:"https://www.bam.org/film/2026/arthouse-scifi-solaris",
  tetsuo:"https://www.bam.org/film/2026/arthouse-scifi-tetsuo",
  silver:"https://www.bam.org/film/2026/arthouse-scifi-on-the-silver-globe",
  laJetee:"https://www.bam.org/film/2026/arthouse-scifi-la-jetee",
  alphaville:"https://www.bam.org/film/2026/arthouse-scifi-alphaville",
  space:"https://www.bam.org/film/2026/arthouse-scifi-space-is-the-place",
  happy:"https://metrograph.com/film/?vista_film_id=9999001933",
  house:"https://metrograph.com/film/?vista_film_id=9999003307",
  days:"https://metrograph.com/film/?vista_film_id=9999004969",
  marnie:"https://metrograph.com/film/?vista_film_id=9999004968",
  laNotte:"https://metrograph.com/film/?vista_film_id=9999004957",
  akira:"https://movingimage.org/event/akira-2026/",
  lateFame:"https://filmforum.org/film/late-fame",
  sherman:"https://filmforum.org/film/shermans-march",
  camp:"https://nitehawkcinema.com/williamsburg/movies/teenage-sex-and-death-at-camp-miasma/",
  franz:"https://quadcinema.com/film/franz/",
  sadWorld:"https://quadcinema.com/film/a-sad-and-beautiful-world/",
  howDivorce:"https://www.ifccenter.com/films/how-to-divorce-during-the-war/",
  itEnds:"https://www.ifccenter.com/films/it-ends/",
  wild:"https://www.ifccenter.com/films/wild-inside/",
  sun:"https://www.ifccenter.com/films/the-sun-never-sets/",
  mubi:"https://mubi.com/en/us/go",
  mulholland:"https://metrograph.com/film/?vista_film_id=9999002169",
  goodbye:"https://metrograph.com/film/?vista_film_id=9999000006",
  brighter:"https://metrograph.com/film/?vista_film_id=9999002246",
  hope:"https://www.neonrated.com/film/hope",
  filipinana:"https://filmforum.org/film/filipinana",
};

const images = {
  memoria:"https://images.squarespace-cdn.com/content/60455d6a513f6b5c4dccdb4c/1642262204247-XSMTDI7M5DKLPAWUQNYX/Memoria%2Bposter.jpg?content-type=image%2Fjpeg&format=1500w",
  stalker:"https://playhousecinema.ca/files/princesscinemas/movie-posters/stalker.jpeg",
  happy:"https://metadata-static.plex.tv/b/gracenote/b8e22415f15fd5a983ceaaeb1eba7612.jpg",
  solaris:"https://cdn.posteritati.com/posters/000/000/067/775/solaris-md-web.jpg",
  house:"https://i.etsystatic.com/29653518/r/il/707a58/6300546825/il_fullxfull.6300546825_r1z8.jpg",
  tetsuo:"https://image.tmdb.org/t/p/original/A2fxnPL2O6zsblGxONM7rt5MlW4.jpg",
  akira:"https://all.web.img.acsta.net/r_2500_x/img/68/bf/68bfcf8b4b431b57ab72a9992e985dae.jpg",
  days:"https://cdn.posteritati.com/posters/000/000/010/703/days-and-nights-in-the-forest-md-web.jpg",
  lateFame:"https://www.newdvdreleasedates.com/images/posters/late-fame-2025.jpg",
  camp:"https://images.justwatch.com/poster/345804971/s718/teenage-sex-and-death-at-camp-miasma.jpg",
  franz:"https://image.pmgstatic.com/cache/resized/w663/files/images/film/posters/170/937/170937576_6hsbhu.jpg",
  sadWorld:"https://images.squarespace-cdn.com/content/v1/5729202420c647e5196d1698/576aac09-2783-4acc-990e-8a716c1af93a/poster%2Bbelgium_page-0001%2Bcopy.jpg?format=1000w",
  divorce:"https://m.media-amazon.com/images/M/MV5BNzJlOWM3MzgtOGMyZi00NTRlLThkZmMtNTg4Yzc1MGViMWNkXkEyXkFqcGc%40._V1_FMjpg_UX1000_.jpg",
  itEnds:"https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak%3D/v3/t/assets/p30145695_v_v8_aa.jpg",
  sherman:"https://s3.amazonaws.com/nightjarprod/content/uploads/sites/243/2026/06/24115915/unnamed-1.jpg",
  laNotte:"https://m.media-amazon.com/images/M/MV5BN2QyMDhkOTctNDhjNC00NjFjLTliMDAtMGE1MDY3NjAzNDhlXkEyXkFqcGc%40._V1_.jpg",
  silver:"https://static1.squarespace.com/static/5e1fec6b1e0b0b52a7cb7211/5e1fed474301a9378dbedebb/68badaaa0a25ad49eef5dd46/1757076703500/on%2Bthe%2Bsilver%2Bglobe.jpg?format=1500w",
  mulholland:"https://static.cinemagia.ro/img/resize/db/movie/00/25/16/mulholland-drive-311011l-576x0-w-07d0f923.jpg",
  goodbye:"https://teatenerife.es/verImagen/news/DKSxQWS5oswW6IBUOZoH.jpg/thumbs",
  brighter:"https://cdn.bingebase.com/movies/23741/posters/3l8fOAwiN3N5n3hHnZ51eog7Zu2.webp",
  hope:"https://www.harpersbazaar.co.kr/resources/online/online_image/2026/06/18/b736bfc3-4d39-4a38-af6e-f0778599c6dd.jpg",
  filipinana:"https://images.squarespace-cdn.com/content/v1/5a6db6f7bce1769a4f753bf1/1768972921424-L9IBE57QR001HCQKIDAS/Filipinana%2B011520261.jpg",
};

const cardBg=(image:string)=>({backgroundImage:`linear-gradient(180deg,rgba(5,6,8,.18),rgba(5,6,8,.78) 43%,rgba(5,6,8,.97) 84%),url(\"${image}\")`});
function Tag({children}:{children:React.ReactNode}){return <span className="tag">{children}</span>}
function TimeLink({href,children}:{href:string;children:React.ReactNode}){return <a className="time-link" href={href} target="_blank" rel="noreferrer">{children}</a>}
type Film={title:string;year:string;region:string;director:string;type:string;venue:string;when:string;format?:string;event?:string;tags?:string[];text:string;href:string;image:string};
function FilmCard({film}:{film:Film}){return <article className="film-card image-card" style={cardBg(film.image)}><div className="tags">{film.tags?.map(t=><Tag key={t}>{t}</Tag>)}</div><h3>{film.title}</h3><dl><div><dt>YEAR / REGION</dt><dd>{film.year} · {film.region}</dd></div><div><dt>DIRECTOR</dt><dd>{film.director}</dd></div><div><dt>TYPE</dt><dd>{film.type}</dd></div><div><dt>VENUE</dt><dd>{film.venue}</dd></div><div><dt>WHEN</dt><dd><TimeLink href={film.href}>{film.when}</TimeLink></dd></div>{film.format&&<div><dt>FORMAT</dt><dd>{film.format}</dd></div>}{film.event&&<div><dt>EVENT</dt><dd>{film.event}</dd></div>}</dl><p>{film.text}</p><a href={film.href} target="_blank" rel="noreferrer">Official listing ↗</a></article>}

const picks=[
 {rank:"01",title:"Memoria",note:"Apichatpong Weerasethakul · 2021 · Colombia/Thailand",when:"Sat Aug 22 · 5:00 PM / Thu Aug 27 · 6:45 PM",venue:"BAM Rose Cinemas",tags:["SPECIAL FOCUS","35MM"],href:links.memoria,image:images.memoria,reason:"A film conceived around communal listening, back on 35mm. Thursday is the cleanest choice if you want Hamaguchi on Saturday."},
 {rank:"02",title:"Happy Hour",note:"Ryūsuke Hamaguchi · 2015 · Japan",when:"Sat Aug 22 · 2:10 PM",venue:"Metrograph",tags:["SPECIAL FOCUS","RARE SCREENING"],href:links.happy,image:images.happy,reason:"Five hours of friendship, marriage and barely perceptible emotional shifts—the early masterwork that made Hamaguchi’s later international breakthrough possible."},
 {rank:"03",title:"Stalker",note:"Andrei Tarkovsky · 1979 · USSR",when:"Sat Aug 22 · 7:45 PM / Wed Aug 26 · 6:30 PM",venue:"BAM Rose Cinemas",tags:["SPECIAL FOCUS","CANON"],href:links.stalker,image:images.stalker,reason:"Protect Wednesday: Saturday follows a five-hour Happy Hour too tightly and overlaps Memoria. Tarkovsky’s Zone remains one of cinema’s great spaces for thought."},
 {rank:"04",title:"AKIRA",note:"Katsuhiro Ōtomo · 1988 · Japan",when:"Thu Aug 27 · 6:30 PM",venue:"Museum of the Moving Image",tags:["4K RESTORATION","DISCUSSION","FREE RSVP"],href:links.akira,image:images.akira,reason:"The new 4K restoration is preceded by a discussion with manga editor Takeshi Katsurada. A major anime landmark with event-level context."},
 {rank:"05",title:"How to Divorce During the War",note:"Andrius Blaževičius · 2026 · Lithuania",when:"Fri & Sat Aug 21–22 · 6:40 PM",venue:"IFC Center",tags:["DIRECTOR Q&A","SUNDANCE WINNER"],href:links.howDivorce,image:images.divorce,reason:"A marriage breakup set against Russia’s invasion of Ukraine, with Blaževičius at both evening screenings. Friday is sold out; Saturday was ticketed at verification."},
 {rank:"06",title:"Teenage Sex and Death at Camp Miasma",note:"Jane Schoenbrun · 2026 · USA",when:"Aug 21–27 · daily",venue:"Nitehawk Williamsburg",tags:["MUBI","CANNES 2026","CULT NEW RELEASE"],href:links.camp,image:images.camp,reason:"Schoenbrun turns a slasher reboot into a theory-soaked queer confrontation between authorship, fandom and the body—an unusually direct match for your recent-cult taste."},
 {rank:"07",title:"Late Fame",note:"Kent Jones · 2025 · USA",when:"Aug 21–27 · 12:15 PM",venue:"Film Forum",tags:["MUBI","VENICE 2025"],href:links.lateFame,image:images.lateFame,reason:"A one-week reprise keeps Jones’s gentle New York literary drama accessible after its high-profile opening Q&As. Dafoe’s inward performance is the reason to go."},
 {rank:"08",title:"Sherman’s March",note:"Ross McElwee · 1986 · USA",when:"Aug 21–27 · daily",venue:"Film Forum",tags:["NEW 4K RESTORATION","DOCUMENTARY CANON"],href:links.sherman,image:images.sherman,reason:"McElwee’s attempt at a Civil War documentary keeps being invaded by desire and autobiography. The restoration revives a foundational first-person documentary on a proper screen."},
];

const focus:Film[]=[
 {title:"Memoria",year:"2021",region:"Colombia / Thailand",director:"Apichatpong Weerasethakul",type:"Slow cinema · sonic mystery",venue:"BAM Rose Cinemas",when:"Sat Aug 22 · 5:00 PM; Thu Aug 27 · 6:45 PM",format:"35mm",tags:["SPECIAL FOCUS","35MM"],text:"A botanist hears an impossible sound and follows it into Colombia’s buried memory. The rare 35mm return is the week’s most medium-specific Special Focus engagement.",href:links.memoria,image:images.memoria},
 {title:"Happy Hour / ハッピーアワー",year:"2015",region:"Japan",director:"Ryūsuke Hamaguchi",type:"Ensemble drama · long-form cinema",venue:"Metrograph",when:"Sat Aug 22 · 2:10 PM",format:"DCP · 317 min",tags:["SPECIAL FOCUS","RARE SCREENING"],text:"Four Kobe friends discover how much remains unsaid inside long relationships. Its five-hour duration is not a stunt: Hamaguchi uses time to make listening, hesitation and social performance physically legible.",href:links.happy,image:images.happy},
 {title:"Stalker / Сталкер",year:"1979",region:"USSR",director:"Andrei Tarkovsky",type:"Metaphysical science fiction",venue:"BAM Rose Cinemas",when:"Sat Aug 22 · 7:45 PM; Wed Aug 26 · 6:30 PM",format:"DCP",tags:["SPECIAL FOCUS","CANON"],text:"A guide leads a writer and scientist through the forbidden Zone toward a room said to reveal deepest desire. Wednesday avoids the week’s major Saturday conflicts.",href:links.stalker,image:images.stalker},
 {title:"Solaris / Солярис",year:"1972",region:"USSR",director:"Andrei Tarkovsky",type:"Metaphysical science fiction",venue:"BAM / Metrograph",when:"BAM Fri Aug 21 · 6:45 PM; Tue Aug 25 · 8:30 PM; Metrograph Wed Aug 26 · 9:00 PM",format:"DCP",tags:["SPECIAL FOCUS"],text:"Tarkovsky turns space travel inward, materializing grief and memory aboard a failing station. BAM’s two dates make this the easier Tarkovsky to schedule around Stalker.",href:links.solaris,image:images.solaris},
];

const asian:Film[]=[
 {title:"Tetsuo: The Iron Man / 鉄男",year:"1989",region:"Japan",director:"Shinya Tsukamoto",type:"Cyberpunk body horror",venue:"BAM Rose Cinemas",when:"Tue Aug 25 · 6:45 PM; Wed Aug 26 · 9:45 PM",format:"DCP",tags:["CULT CANON","ASIAN CINEMA"],text:"A salaryman’s body erupts into metal in 67 pulverizing minutes. Its handmade industrial assault connects cyberpunk, Cronenberg and Lynch—and it still feels dangerous in a theater.",href:links.tetsuo,image:images.tetsuo},
 {title:"House / ハウス",year:"1977",region:"Japan",director:"Nobuhiko Ōbayashi",type:"Psychedelic horror comedy",venue:"Metrograph",when:"Fri Aug 21 · 11:00 PM; Mon Aug 24 · 7:45 PM",format:"35mm",tags:["35MM","CULT CANON"],text:"Seven schoolgirls enter a haunted house that seems edited by a sugar-rushing child. The tactile 35mm print is exactly the right vessel for Ōbayashi’s exuberant analog effects.",href:links.house,image:images.house},
 {title:"Days and Nights in the Forest / অরণ্যের দিনরাত্রি",year:"1970",region:"India",director:"Satyajit Ray",type:"Drama · social satire",venue:"Metrograph",when:"Sat Aug 22 · 2:30 PM",format:"4K DCP",tags:["4K","ASIAN CANON"],text:"Four Calcutta friends flee to the countryside and discover how little distance separates leisure from cruelty. Ray’s ensemble staging and moral calibration make the restoration a major alternative to Happy Hour.",href:links.days,image:images.days},
 {title:"AKIRA / アキラ",year:"1988",region:"Japan",director:"Katsuhiro Ōtomo",type:"Cyberpunk animation",venue:"Museum of the Moving Image",when:"Thu Aug 27 · 6:30 PM",format:"New 4K restoration",event:"Pre-screening discussion with manga editor Takeshi Katsurada; free with RSVP",tags:["4K RESTORATION","EVENT"],text:"Neo-Tokyo’s youth revolt, psychic violence and hand-drawn scale still overwhelm the screen. Katsurada’s participation turns a familiar classic into a singular film-culture event.",href:links.akira,image:images.akira},
];

const festival:Film[]=[
 {title:"Late Fame",year:"2025",region:"USA",director:"Kent Jones",type:"Literary drama",venue:"Film Forum",when:"Aug 21–27 · 12:15 PM",format:"DCP",tags:["VENICE 2025 · ORIZZONTI","MUBI"],text:"A forgotten poet is rediscovered by young admirers and tempted by recognition. Jones’s modest scale and Dafoe’s restraint suit the one-week reprise better than the louder prestige framing around it.",href:links.lateFame,image:images.lateFame},
 {title:"Franz",year:"2025",region:"Czech Republic / Germany / Poland",director:"Agnieszka Holland",type:"Kaleidoscopic biographical drama",venue:"Quad Cinema",when:"Aug 21–27 · daily",format:"DCP",tags:["SAN SEBASTIÁN 2025 · OFFICIAL SELECTION"],text:"Holland builds Kafka’s life as a fragmented mosaic rather than a tidy cradle-to-grave biography. It is the newest eligible European-festival discovery with the broadest daily availability.",href:links.franz,image:images.franz},
 {title:"A Sad and Beautiful World",year:"2025",region:"Lebanon",director:"Cyril Aris",type:"Romantic drama",venue:"Quad Cinema",when:"Aug 21–27 · daily",format:"DCP",tags:["VENICE 2025 · GIORNATE DEGLI AUTORI","MIDDLE EAST"],text:"A relationship unfolds against Lebanon’s shifting political and social landscape. Its regional focus and recent Venice sidebar pedigree make it more than a residual holdover.",href:links.sadWorld,image:images.sadWorld},
 {title:"Teenage Sex and Death at Camp Miasma",year:"2026",region:"USA",director:"Jane Schoenbrun",type:"Meta-slasher",venue:"Nitehawk Williamsburg",when:"Aug 21–27 · daily",format:"DCP",tags:["CANNES 2026 · UN CERTAIN REGARD","MUBI"],text:"A young director revives a cult slasher with its original final girl—and discovers the franchise staring back. The current NYC run is the festival section’s most contemporary cult proposition.",href:links.camp,image:images.camp},
];

const classics:Film[]=[
 {title:"La Notte",year:"1961",region:"Italy / France",director:"Michelangelo Antonioni",type:"Modernist relationship drama",venue:"Metrograph",when:"Fri Aug 21 · 5:45 PM; Wed Aug 26 · 2:00 PM",format:"DCP",tags:["MODERNIST CANON"],text:"A marriage’s exhaustion is mapped across hospital rooms, glass towers and an all-night party. Antonioni’s architecture and negative space gain force at theatrical scale.",href:links.laNotte,image:images.laNotte},
 {title:"On the Silver Globe / Na srebrnym globie",year:"1988",region:"Poland",director:"Andrzej Żuławski",type:"Unfinished science-fiction epic",venue:"BAM Rose Cinemas",when:"Sun Aug 23 · 5:50 PM; Mon Aug 24 · 4:00 PM",format:"DCP",tags:["RARE SCREENING","CULT CANON"],text:"Suppressed during production and reconstructed years later, Żuławski’s lunar epic looks like civilization being invented and destroyed at once. Its incompleteness is part of its convulsive power.",href:links.silver,image:images.silver},
 {title:"Sherman’s March",year:"1986",region:"USA",director:"Ross McElwee",type:"First-person documentary",venue:"Film Forum",when:"Aug 21–27 · daily",format:"New 4K restoration",tags:["NEW RESTORATION","DOCUMENTARY CANON"],text:"A historical project detours into romance, self-exposure and the texture of the American South. The restoration returns a hugely influential essay film to the communal setting it helped redefine.",href:links.sherman,image:images.sherman},
];

const newHits:Film[]=[
 {title:"How to Divorce During the War",year:"2026",region:"Lithuania",director:"Andrius Blaževičius",type:"Domestic drama · black comedy",venue:"IFC Center",when:"Aug 21–27 · daily; Q&As Fri/Sat 6:40 PM",format:"DCP",event:"Director Andrius Blaževičius; Fri sold out, Sat on sale",tags:["SUNDANCE DIRECTING WINNER","DIRECTOR Q&A"],text:"A Vilnius couple tries to end a marriage as a neighboring war transforms private crisis into moral pressure. Saturday’s available Q&A is the best entry point.",href:links.howDivorce,image:images.divorce},
 {title:"It Ends",year:"2026",region:"USA",director:"Alex Ullom",type:"Independent horror · road nightmare",venue:"IFC Center",when:"Aug 21–27 · daily; Q&As Fri/Sat 7:10 PM, Sun 4:55 PM",format:"DCP",event:"Director Alex Ullom at all three listed shows",tags:["DIRECTOR Q&A","CULT-LEANING"],text:"Recent graduates turn onto a road that refuses to end. Ullom’s resourceful debut converts a stripped-down premise into a chamber piece about friendship and dread.",href:links.itEnds,image:images.itEnds},
];

const worth:Film[]=[
 {title:"How to Divorce During the War",year:"2026",region:"Lithuania",director:"Andrius Blaževičius",type:"Drama · black comedy",venue:"IFC Center",when:"Sat Aug 22 · 6:40 PM Q&A; daily run Aug 21–27",format:"DCP",event:"Director Q&A; Friday event show sold out",tags:["DIRECTOR Q&A"],text:"If the Special Focus marathon is too heavy, this is the week’s strongest filmmaker-attended contemporary alternative. Saturday retains the guest value without Friday’s sellout.",href:links.howDivorce,image:images.divorce},
 {title:"La Jetée + The Last Angel of History",year:"1962 / 1996",region:"France / UK",director:"Chris Marker / John Akomfrah",type:"Essay film · Afrofuturist hybrid",venue:"BAM Rose Cinemas",when:"Sat Aug 22 · 1:00 PM; Mon Aug 24 · 9:15 PM",format:"DCP / digital",tags:["DOUBLE FEATURE","ESSAY CINEMA"],text:"Marker’s still-image time-travel classic meets Akomfrah’s excavation of Black music and future technology. The pairing makes history itself feel like a transmission medium.",href:links.laJetee,image:images.silver},
];

const noteworthy:Film[]=[
 {title:"BAM Arthouse Sci‑Fi",year:"1962–2021",region:"International",director:"Godard, Tarkovsky, Marker, Akomfrah, Borden, Cronenberg, Weerasethakul & more",type:"Thematic repertory series",venue:"BAM Rose Cinemas",when:"Aug 21–27",format:"35mm and DCP by title",tags:["MAJOR SERIES","SPECIAL FOCUS"],text:"The series treats science fiction as a laboratory for memory, politics, Afrofuturism, feminism and body horror. It is the week’s defining program; the individual Tarkovsky and Apichatpong titles are separated above so they cannot be missed.",href:links.bamSciFi,image:images.memoria},
 {title:"Saturday Afternoon Cartoons: Bugs We Love(?)",year:"1950s program",region:"USA",director:"Multiple",type:"Animation program",venue:"Metrograph",when:"Sat Aug 22 · 12:15 PM",format:"16mm",event:"Introduction and Q&A with film historian Tommy J. Stathes",tags:["16MM","Q&A"],text:"A compact 16mm program restores theatrical cartoons to their original social setting. Stathes’s archive knowledge gives the event more weight than a nostalgia matinee.",href:"https://metrograph.com/film/?vista_film_id=9999004979",image:images.house},
];

const coming:Film[]=[
 {title:"Mulholland Drive",year:"2001",region:"USA / France",director:"David Lynch",type:"Dream-noir · psychological mystery",venue:"Metrograph",when:"Sat Aug 29 · 10:30 PM; Sun Aug 30 · 4:00 PM; Sat Sep 5 · 10:45 PM",format:"35mm",tags:["SPECIAL FOCUS","35MM"],text:"A direct Lynch match and one of the defining films of the century. The late Saturday print screening is ideal, but the Sunday matinee is the safer practical choice.",href:links.mulholland,image:images.mulholland},
 {title:"Goodbye, Dragon Inn / 不散",year:"2003",region:"Taiwan",director:"Tsai Ming-liang",type:"Slow cinema · movie-palace elegy",venue:"Metrograph",when:"Sun Aug 30 · 11:15 AM",format:"DCP",tags:["SPECIAL FOCUS","RARE SCREENING"],text:"Tsai’s near-wordless farewell to a dying cinema should be seen inside one. This is exactly the kind of one-off Special Focus screening the 30-day sweep exists to protect.",href:links.goodbye,image:images.goodbye},
 {title:"A Brighter Summer Day / 牯嶺街少年殺人事件",year:"1991",region:"Taiwan",director:"Edward Yang",type:"Historical youth epic",venue:"Metrograph",when:"Sat Sep 5 · 1:35 PM; Mon Sep 7 · 5:15 PM",format:"DCP",tags:["SPECIAL FOCUS","ASIAN CANON"],text:"Yang’s four-hour epic turns a teenage murder case into a social history of Taiwan. Two dates make this a rare but schedulable direct hit.",href:links.brighter,image:images.brighter},
 {title:"Hope",year:"2026",region:"South Korea",director:"Na Hong-jin",type:"Supernatural thriller",venue:"NYC venue TBA",when:"Wed Sep 9 · NYC opening",format:"TBA",tags:["NEON","SPECIAL FOCUS DISTRIBUTOR"],text:"Na Hong-jin’s long-awaited return is the 30-day window’s most important NEON release for your Korean and cult-horror interests. Exact NYC theater and showtimes remain unannounced; track NEON’s page.",href:links.hope,image:images.hope},
 {title:"The Sun Never Sets",year:"2026",region:"USA",director:"Joe Swanberg",type:"Independent relationship comedy",venue:"IFC Center",when:"Fri Sep 4 · regular engagement opens",format:"DCP",tags:["NEW RELEASE"],text:"Dakota Fanning anchors Swanberg’s Anchorage-set return to intimate relationship comedy. The Aug 22 sneak preview has the week’s star Q&A; the regular run begins September 4 with times TBA.",href:links.sun,image:images.itEnds},
 {title:"Filipiñana",year:"2024",region:"Philippines",director:"Rafael Manuel",type:"Social drama",venue:"Film Forum",when:"Fri Aug 28 · NYC opening",format:"DCP",tags:["NEW RELEASE","SOUTHEAST ASIA"],text:"A young golf-club worker observes the rituals and violence of elite leisure. Its Filipino perspective and formally controlled class critique make it the strongest Asian opening immediately after this week.",href:links.filipinana,image:images.filipinana},
];

const events=[
 {date:"AUG 21 · 6:40 PM",title:"How to Divorce During the War — director Q&A",href:links.howDivorce,body:"IFC Center · director Andrius Blaževičius. SOLD OUT at verification."},
 {date:"AUG 21 · 7:10 PM; AUG 22 · 7:10 PM; AUG 23 · 4:55 PM",title:"It Ends — Alex Ullom Q&As",href:links.itEnds,body:"IFC Center · director Alex Ullom at each listed event-bearing show. Tickets on sale."},
 {date:"AUG 21 · 7:00 PM; AUG 22 · 9:30 PM",title:"Lockjaw — Q&As",href:"https://www.roxycinemanewyork.com/events/qa-with-sabrina-greco-and-blu-hunt-2/",body:"Roxy Cinema · director Sabrina Greco and actor Blu Hunt at both; Megan Bitchell moderates Aug 22. Tickets on sale."},
 {date:"AUG 22 · 1:50 PM",title:"Wild Inside — Q&A",href:links.wild,body:"IFC Center · director Penny Lane; filmmaker Matt Wolf moderates. Tickets on sale."},
 {date:"AUG 22 · 2:30 PM",title:"The Sun Never Sets — sneak preview + Q&A",href:links.sun,body:"IFC Center · actors Dakota Fanning and Cory Michael Smith. Tickets on sale; regular engagement begins Sep 4."},
 {date:"AUG 22 · 6:40 PM",title:"How to Divorce During the War — director Q&A",href:links.howDivorce,body:"IFC Center · director Andrius Blaževičius. Tickets were available at verification."},
 {date:"AUG 22 · 12:15 PM",title:"Saturday Afternoon Cartoons — intro + Q&A",href:"https://metrograph.com/film/?vista_film_id=9999004979",body:"Metrograph · film historian and archivist Tommy J. Stathes presents the 16mm program. Tickets on sale."},
 {date:"AUG 25 · 6:00 PM",title:"Tracking Shots — archive-film presentation",href:"https://filmforum.org/events",body:"Film Forum · introduced by Jodi Shapiro, curator at the New York Transit Museum. Tickets on sale."},
 {date:"AUG 25 · 7:00 PM",title:"When We Saw Each Other More Often — Q&A",href:"https://www.roxycinemanewyork.com/events/qa-with-william-wrubel/",body:"Roxy Cinema · writer-director William Wrubel. Tickets on sale."},
 {date:"AUG 26 · 6:00 PM",title:"In the Family — 35mm + Q&A",href:"https://www.roxycinemanewyork.com/events/qa-with-patrick-wang/",body:"Roxy Cinema · actor-director Patrick Wang; critic Keith Uhlich moderates. Tickets on sale."},
 {date:"AUG 27 · 6:30 PM",title:"AKIRA — 4K restoration + discussion",href:links.akira,body:"Museum of the Moving Image · discussion with AKIRA manga editor Takeshi Katsurada precedes the screening. Free with RSVP; reserve promptly."},
 {date:"AUG 27 · 9:00 PM",title:"The Straight Story — 35mm + conversation",href:"https://www.roxycinemanewyork.com/events/qa-with-slow-pulp/",body:"Roxy Cinema · Slow Pulp discuss David Lynch’s film and their new album; @marg.mp3 moderates. Tickets on sale."},
 {date:"AUG 28 · 7:30 PM; AUG 29 · 8:00 PM",title:"Ganz + Streeter: New Discoveries — filmmakers in person",href:"https://www.anthologyfilmarchives.org/film_screenings/series/61608",body:"Anthology Film Archives · Tony Ganz and Rhody Streeter in person at both event-bearing programs. Tickets available at the box office/official listing."},
 {date:"SEP 2 · 6:30 PM",title:"UnionDocs presents Welfare",href:"https://www.anthologyfilmarchives.org/film_screenings/series",body:"Anthology Film Archives · Frederick Wiseman’s institutional epic presented with UnionDocs. Ticket status via Anthology."},
 {date:"SEP 5 · 6:00 PM",title:"Wiseman’s NYC: Model — introduction",href:"https://metrograph.com/film/",body:"Metrograph · introduction by film scholar Genevieve Yue, lead facilitator of Wiseman’s New York. Tickets on sale."},
 {date:"SEP 12 · 5:00 PM",title:"Short film screening + Q&A",href:"https://www.roxycinemanewyork.com/events/qa-with-sam-taffel-gillian-waldo/",body:"Roxy Cinema · filmmakers Sam Taffel and Gillian Waldo. Tickets listed."},
 {date:"SEP 15 · 7:00 PM",title:"Soul Patrol — NYC premiere + Q&A",href:"https://www.ifccenter.com/films/soul-patrol/",body:"IFC Center / DOC NYC Selects · filmmaker J.M. Harper. Tickets on sale."},
 {date:"SEP 17 · 7:30 PM",title:"Go Go Go Slow — book release event",href:"https://www.anthologyfilmarchives.org/film_screenings/series",body:"Anthology Film Archives · cinema-related book release program; participant details not yet published on the official calendar. Ticket status TBA."},
];

export default function Home(){return <main>
 <header className="mast"><a className="brand" href="#top"><span className="brand-reel">●</span> NYC / ARTHOUSE <span className="brand-film">35MM</span></a><nav aria-label="Primary navigation"><a href="#picks">This Week</a><a href="#special">Special Focus</a><a href="#asian">Asian</a><a href="#festival">Festival</a><a href="#soon">Coming Soon</a><a href="#events">Events</a><a href="#archive">Archive</a></nav></header>
 <section className="hero" id="top"><div className="hero-rotator" aria-hidden="true"><span style={{backgroundImage:`url("${images.memoria}")`}}/><span style={{backgroundImage:`url("${images.happy}")`}}/><span style={{backgroundImage:`url("${images.stalker}")`}}/></div><div className="hero-shade" aria-hidden="true"/><div className="eyebrow hero-content"><span>✦ WEEK 03</span><span>NOW SHOWING · NEW YORK</span></div><div className="hero-title-wrap hero-content"><span className="projector-mark">◉</span><h1>NYC Arthouse<br/><em>Film Guide</em></h1><span className="film-strip">▯ ▯ ▯ ▯ ▯ ▯</span></div><div className="hero-foot hero-content"><p className="range">AUG 21 → 27 <sup>2026</sup></p><p className="dek">A personal weekly map of repertory, international and independent cinema—weighted toward Asian cinema, rare prints, cult canon and filmmaker appearances.</p></div></section>
 <section className="three"><div><p className="kicker">🎟 IF I COULD ONLY SEE THREE</p></div><ol><li><b>MEMORIA</b><span>Apichatpong · 35mm</span></li><li><b>HAPPY HOUR</b><span>Hamaguchi · rare five-hour screening</span></li><li><b>STALKER</b><span>Tarkovsky · protect Wednesday</span></li></ol></section>
 <section className="mubi-band image-band" style={cardBg(images.lateFame)}><div><p className="kicker">🎫 MUBI GO THIS WEEK</p><h2>Upcoming pick not public yet</h2></div><div className="mubi-copy"><p><b>Covered eligibility window: Aug 21–27</b></p><p>MUBI’s public GO page did not expose the next NYC title before this edition’s publication. The confirmed Aug 14–20 pick is <i>Late Fame</i>; do not assume that its MUBI distribution—or <i>Camp Miasma</i> opening wider—determines the next offer.</p><p>Open the MUBI GO app after the weekly rollover to confirm the Aug 21–27 title, eligible NYC cinema and showtime before redeeming.</p><a className="arrow" href={links.mubi} target="_blank" rel="noreferrer">MUBI GO ↗</a></div></section>
 <section className="section" id="picks"><div className="section-head"><p className="kicker">01 / 🎬 THIS WEEK</p><h2>Top picks</h2><p>The films worth actively protecting time for—not a quota-driven calendar dump.</p></div><div className="pick-list">{picks.map(p=><article className="pick image-pick" style={cardBg(p.image)} key={p.rank}><div className="rank">{p.rank}</div><div className="pick-main"><div className="tags">{p.tags.map(t=><Tag key={t}>{t}</Tag>)}</div><h3>{p.title}</h3><p className="meta">{p.note}</p><p>{p.reason}</p></div><div className="showtime"><b>{p.when}</b><span>{p.venue}</span><a href={p.href} target="_blank" rel="noreferrer">Official listing ↗</a></div></article>)}</div></section>
 <section className="alert"><span>⚡ CONFLICT WATCH</span><p><b>Saturday is impossible to complete as a marathon:</b> <i>Happy Hour</i> runs 2:10–about 7:27 PM at Metrograph, overlapping <i>Memoria</i> at 5:00 and leaving no viable transfer to <i>Stalker</i> at 7:45 at BAM. Choose <i>Happy Hour</i> Saturday, then <i>Stalker</i> Wednesday and <i>Memoria</i> Thursday.</p></section>
 <section className="section dark" id="special"><div className="section-head"><p className="kicker">02 / 🎯 SPECIAL FOCUS</p><h2>Direct matches</h2><p>Four unequivocal filmmaker matches in the seven-day window.</p></div><div className="card-grid">{focus.map(f=><FilmCard key={f.title} film={f}/>)}</div></section>
 <section className="section" id="asian"><div className="section-head"><p className="kicker">03 / 🌏 ASIAN CINEMA</p><h2>From Kobe to Neo‑Tokyo</h2><p>Long-form realism, handmade cyberpunk, cult horror and canonical restoration work.</p></div><div className="card-grid">{asian.map(f=><FilmCard key={f.title} film={f}/>)}</div></section>
 <section className="section dark" id="festival"><div className="section-head"><p className="kicker">04 / 🏆 FESTIVAL</p><h2>Recent European-festival discoveries</h2><p>Only current NYC screenings with verified selections from the five most recent eligible festival editions.</p></div><div className="card-grid">{festival.map(f=><FilmCard key={f.title} film={f}/>)}</div></section>
 <section className="section blue" id="classics"><div className="section-head"><p className="kicker">05 / 🎞 ALL-TIME CLASSICS</p><h2>Restored, radical, inexhaustible</h2><p>Modernist architecture, first-person documentary and a mutilated science-fiction epic.</p></div><div className="card-grid">{classics.map(f=><FilmCard key={f.title} film={f}/>)}</div></section>
 <section className="section" id="new"><div className="section-head"><p className="kicker">06 / 🆕 NEW HITS</p><h2>Opening runs with live context</h2><p>New films whose event-bearing shows justify choosing a specific time.</p></div><div className="card-grid">{newHits.map(f=><FilmCard key={f.title} film={f}/>)}</div></section>
 <section className="section ruled" id="worth"><div className="section-head"><p className="kicker">07 / ⭐ WORTH SEEING</p><h2>Strong alternatives</h2><p>Every card links to the most specific official listing.</p></div><div className="card-grid">{worth.map(f=><FilmCard key={f.title} film={f}/>)}</div></section>
 <section className="section" id="noteworthy"><div className="section-head"><p className="kicker">08 / 🎥 OTHER NOTEWORTHY</p><h2>Programs & experiments</h2><p>Series-level curation and archival presentations beyond individual canon titles.</p></div><div className="card-grid">{noteworthy.map(f=><FilmCard key={f.title} film={f}/>)}</div></section>
 <section className="section schedule dark" id="all-other"><div className="section-head"><p className="kicker">09 / 📋 ALL OTHER SCREENINGS</p><h2>The rest of the map</h2><p>A seven-day shortlist of worthwhile screenings found in the full venue sweep and not featured above. Every time links to its exact official film or program page.</p></div><div className="schedule-grid">
  <div><h3>FRI 21</h3><p>Metrograph — Chungking Express <TimeLink href="https://metrograph.com/film/?vista_film_id=9999000735">12:45 PM</TimeLink>; In the Mood for Love <TimeLink href="https://metrograph.com/film/?vista_film_id=9999000517">3:00 PM</TimeLink>; The Others <TimeLink href="https://metrograph.com/film/?vista_film_id=9999004961">3:30 PM</TimeLink>; The Dark Knight <TimeLink href="https://metrograph.com/film/?vista_film_id=9999003615">5:15 PM</TimeLink>; What Lies Beneath <TimeLink href="https://metrograph.com/film/?vista_film_id=9999004967">8:15 PM</TimeLink>; True Romance <TimeLink href="https://metrograph.com/film/?vista_film_id=9999003371">8:30 PM</TimeLink>. BAM — Alphaville <TimeLink href={links.alphaville}>2:00 PM</TimeLink>; Space Is the Place <TimeLink href={links.space}>4:30 PM</TimeLink>. MoMI — Lawrence of Arabia 70mm <TimeLink href="https://movingimage.org/series/see-it-big-70mm-2026/">6:00 PM</TimeLink>. Anthology — Strangers on a Train <TimeLink href="https://www.anthologyfilmarchives.org/film_screenings/series">7:30 PM</TimeLink>; White Sun of the Desert <TimeLink href="https://www.anthologyfilmarchives.org/film_screenings/series">9:00 PM</TimeLink>.</p></div>
  <div><h3>SAT 22</h3><p>Metrograph — When Marnie Was There <TimeLink href={links.marnie}>12:00 PM</TimeLink>; Bram Stoker’s Dracula <TimeLink href="https://metrograph.com/film/?vista_film_id=9999004970">7:45 PM</TimeLink>; Women on the Verge of a Nervous Breakdown <TimeLink href="https://metrograph.com/film/?vista_film_id=9999003126">10:30 PM</TimeLink>. BAM — Alphaville <TimeLink href={links.alphaville}>2:45 PM</TimeLink>. MoMI — Jaws in Dolby Atmos <TimeLink href="https://movingimage.org/event/jaws-2026/2026-08-22/">1:00 PM</TimeLink>; CatVideoFest <TimeLink href="https://movingimage.org/event/catvideofest-2026/2026-08-22/1/">1:30 / 4:00 PM</TimeLink>; Hamlet 70mm <TimeLink href="https://movingimage.org/series/see-it-big-70mm-2026/">3:30 PM</TimeLink>. Anthology — A Girl Is a Gun <TimeLink href="https://www.anthologyfilmarchives.org/film_screenings/series">4:15 PM</TimeLink>; Deadlock <TimeLink href="https://www.anthologyfilmarchives.org/film_screenings/series/61653">6:45 PM</TimeLink>; Don’t Touch the White Woman! <TimeLink href="https://www.anthologyfilmarchives.org/film_screenings/series/61653">9:00 PM</TimeLink>.</p></div>
  <div><h3>SUN 23</h3><p>Metrograph — When Marnie Was There <TimeLink href={links.marnie}>12:40 PM</TimeLink>; The Dark Knight <TimeLink href="https://metrograph.com/film/?vista_film_id=9999003615">1:30 PM</TimeLink>; Bram Stoker’s Dracula <TimeLink href="https://metrograph.com/film/?vista_film_id=9999004970">6:40 PM</TimeLink>. BAM — Born in Flames <TimeLink href="https://www.bam.org/film/2026/arthouse-scifi-born-in-flames">9:10 PM</TimeLink>. MoMI — The Umbrellas of Cherbourg <TimeLink href="https://movingimage.org/whats-on/screenings-and-series/">1:00 PM</TimeLink>; Lawrence of Arabia 70mm <TimeLink href="https://movingimage.org/series/see-it-big-70mm-2026/">3:00 PM</TimeLink>. Anthology — Apaches <TimeLink href="https://www.anthologyfilmarchives.org/film_screenings/series/61653">3:45 PM</TimeLink>; Abel Raises Cain <TimeLink href="https://www.anthologyfilmarchives.org/film_screenings/series">7:30 PM</TimeLink>.</p></div>
  <div><h3>MON 24</h3><p>Metrograph — Falling Leaves <TimeLink href="https://metrograph.com/film/?vista_film_id=9999004963">5:45 PM</TimeLink>; There Once Was a Singing Blackbird <TimeLink href="https://metrograph.com/film/?vista_film_id=9999004964">7:40 PM</TimeLink>; Wake in Fright <TimeLink href="https://metrograph.com/film/?vista_film_id=9999004939">9:40 PM</TimeLink>; Fallen Angels <TimeLink href="https://metrograph.com/film/?vista_film_id=9999003325">9:45 PM</TimeLink>. BAM — Space Is the Place <TimeLink href={links.space}>7:15 PM</TimeLink>. Anthology — A Girl Is a Gun <TimeLink href="https://www.anthologyfilmarchives.org/film_screenings/series">6:30 PM</TimeLink>; Zachariah <TimeLink href="https://www.anthologyfilmarchives.org/film_screenings/series/61653">9:00 PM</TimeLink>.</p></div>
  <div><h3>TUE 25</h3><p>Metrograph — no public repertory screening beyond a private event was listed at verification. BAM — Solaris <TimeLink href={links.solaris}>8:30 PM</TimeLink>. Anthology — Mad Dog Morgan <TimeLink href="https://www.anthologyfilmarchives.org/film_screenings/series">6:30 PM</TimeLink>; Deadlock <TimeLink href="https://www.anthologyfilmarchives.org/film_screenings/series/61653">9:00 PM</TimeLink>. Film Forum — Tracking Shots <TimeLink href="https://filmforum.org/events">6:00 PM</TimeLink>. Roxy — When We Saw Each Other More Often + Q&A <TimeLink href="https://www.roxycinemanewyork.com/events/qa-with-william-wrubel/">7:00 PM</TimeLink>.</p></div>
  <div><h3>WED 26</h3><p>Metrograph — Girlhood <TimeLink href="https://metrograph.com/film/?vista_film_id=9999004954">2:00 PM</TimeLink>; Les Bonnes Femmes <TimeLink href="https://metrograph.com/film/?vista_film_id=9999002290">4:15 PM</TimeLink>; Before Sunrise <TimeLink href="https://metrograph.com/film/?vista_film_id=9999002387">4:30 PM</TimeLink>; And Then There Was Light <TimeLink href="https://metrograph.com/film/?vista_film_id=9999004956">6:20 PM</TimeLink>; The Hunger <TimeLink href="https://metrograph.com/film/?vista_film_id=9999001195">6:45 PM</TimeLink>; Je Tu Il Elle <TimeLink href="https://metrograph.com/film/?vista_film_id=9999002615">8:30 PM</TimeLink>; Obsession <TimeLink href="https://metrograph.com/film/?vista_film_id=9999000197">10:20 PM</TimeLink>. Anthology — Don’t Touch the White Woman! <TimeLink href="https://www.anthologyfilmarchives.org/film_screenings/series/61653">6:30 PM</TimeLink>; Zachariah <TimeLink href="https://www.anthologyfilmarchives.org/film_screenings/series/61653">9:15 PM</TimeLink>.</p></div>
  <div><h3>THU 27</h3><p>Metrograph — Deliverance <TimeLink href="https://metrograph.com/film/?vista_film_id=9999001370">2:15 PM</TimeLink>; Chocolat <TimeLink href="https://metrograph.com/film/?vista_film_id=9999003839">2:25 PM</TimeLink>; 3 Women <TimeLink href="https://metrograph.com/film/?vista_film_id=9999000915">4:30 PM</TimeLink>; Conversation Piece <TimeLink href="https://metrograph.com/film/?vista_film_id=9999004912">4:45 PM</TimeLink>; Collateral <TimeLink href="https://metrograph.com/film/?vista_film_id=9999004937">7:00 PM</TimeLink>; My Night at Maud’s <TimeLink href="https://metrograph.com/film/?vista_film_id=9999003055">7:15 PM</TimeLink>; Drunken Master II <TimeLink href="https://metrograph.com/film/?vista_film_id=9999004940">9:30 PM</TimeLink>; Love in the Afternoon <TimeLink href="https://metrograph.com/film/?vista_film_id=9999004921">9:35 PM</TimeLink>. Anthology — Essential Cinema: Cavalcanti/Crockwell <TimeLink href="https://www.anthologyfilmarchives.org/film_screenings/series">6:15 PM</TimeLink>; Dead Man <TimeLink href="https://www.anthologyfilmarchives.org/film_screenings/series/61653">6:30 PM</TimeLink>; Essential Cinema: Maya Deren <TimeLink href="https://www.anthologyfilmarchives.org/film_screenings/series">8:15 PM</TimeLink>; Searchers <TimeLink href="https://www.anthologyfilmarchives.org/film_screenings/series/61653">9:15 PM</TimeLink>.</p></div>
 </div></section>
 <section className="section soon" id="soon"><div className="section-head"><p className="kicker">10 / 🔭 COMING SOON</p><h2>Next 30 days</h2><p>Special Focus first, followed by high-fit new releases. Dates are large; unannounced showtimes stay TBA.</p></div><div className="card-grid">{coming.map(f=><FilmCard key={f.title} film={f}/>)}</div></section>
 <section className="section events" id="events"><div className="section-head"><p className="kicker">11 / 🎤 NYC FILM EVENTS</p><h2>30-day event radar</h2><p>Event-bearing showtimes, confirmed guests and moderators, and ticket status. Event titles are the links.</p></div><div className="event-list">{events.map(e=><div key={e.date+e.title}><time>{e.date}</time><h3><a href={e.href} target="_blank" rel="noreferrer">{e.title}</a></h3><p>{e.body}</p></div>)}</div></section>
 <section className="section" id="archive"><div className="section-head"><p className="kicker">🗃 PREVIOUS WEEKS / ARCHIVE</p><h2>Rolling 10-week archive</h2></div><div className="mini-grid"><article><Tag>WEEK 02</Tag><h3>Aug 14–20, 2026</h3><p>Ōshima, Irréversible, 2001 in 70mm, Ozu and the August event radar.</p><a href="/chrisfilmguide/archive/week-02/">Open archived edition ↗</a></article><article><Tag>WEEK 01</Tag><h3>Aug 8–14, 2026</h3><p>The Hole, Late Fame, Millennium Mambo, Center Stage and the first August event radar.</p><a href="/chrisfilmguide/archive/week-01/">Open archived edition ↗</a></article></div></section>
 <footer><p><b>IF I COULD ONLY SEE THREE:</b> Memoria · Happy Hour · Stalker</p><p>Times, formats, guests and ticket status verified against official listings on Aug 20, 2026. Recheck before travel; schedules can change.</p></footer>
 </main>}
