const L={mubi:'https://mubi.com/en/us/go',pure:'https://www.bam.org/film/2026/a-pure-person',mambo:'https://www.bam.org/film/2026/a-pure-person-millennium-mambo',assassin:'https://www.bam.org/film/2026/a-pure-person-the-assassin',world:'https://www.bam.org/film/2026/a-pure-person-the-world',tides:'https://www.bam.org/film/2026/a-pure-person-caught-by-the-tides',jinpa:'https://www.bam.org/film/2026/a-pure-person-jinpa',kaili:'https://www.bam.org/film/2026/a-pure-person-kaili-blues',stray:'https://metrograph.com/film/?vista_film_id=9999004997',yiyi:'https://metrograph.com/film/?vista_film_id=9999001293',brighter:'https://metrograph.com/film/?vista_film_id=9999002246',rebels:'https://metrograph.com/film/?vista_film_id=9999003028',left:'https://metrograph.com/film/?vista_film_id=9999004996',paprika:'https://metrograph.com/film/?vista_film_id=9999002029',ghost:'https://metrograph.com/film/?vista_film_id=9999000710',blade:'https://metrograph.com/film/?vista_film_id=9999000127',concrete:'https://www.ifccenter.com/films/the-history-of-concrete/',arsa:'https://www.ifccenter.com/films/arsa/',serpent:'https://www.ifccenter.com/films/serpents-path/',franz:'https://quadcinema.com/film/franz/',fisherman:'https://quadcinema.com/film/the-fisherman/',checkout:'https://quadcinema.com/film/checkout/',totally:'https://quadcinema.com/film/totally-fed-up/',primetime:'https://www.bam.org/film/2026/primetime',incomer:'https://www.ifccenter.com/films/the-incomer/',nyff:'https://www.filmlinc.org/nyff2026/',possible:'https://www.filmlinc.org/nyff2026/films/possible-love/',hamaguchi:'https://www.filmlinc.org/nyff2026/events/amos-vogel-lecture-hamaguchi/',cameron:'https://www.filmlinc.org/nyff2026/films/cameron-winter-at-carnegie/',fielder:'https://www.filmlinc.org/daily/nathan-fielder-and-lance-oppenheims-you-can-see-everything-added-to-64th-new-york-film-festival-spotlight/',still:'https://www.anthologyfilmarchives.org/film_screenings/programs/series/61953',scorsese:'https://www.bam.org/talks/2026/the-third-eye',scout:'https://filmforum.org/events/event/the-scout-september-24',eddington:'https://metrograph.com/film/?vista_film_id=9999005008'};
const I={concrete:'https://images.mubicdn.net/images/film/461757/cache-1154970-1789037270/image-w1280.jpg',mambo:'https://www.bam.org/globalassets/programs/cinema/2027fy/0926/a-pure-person-the-sonic-landscape-of-lim-giong/milennium-mambo.jpg',assassin:'https://www.bam.org/globalassets/programs/cinema/2027fy/0926/a-pure-person-the-sonic-landscape-of-lim-giong/the-assassin.jpg',world:'https://www.bam.org/globalassets/programs/cinema/2027fy/0926/a-pure-person-the-sonic-landscape-of-lim-giong/the-world.jpg',tides:'https://www.bam.org/globalassets/programs/cinema/2027fy/0926/a-pure-person-the-sonic-landscape-of-lim-giong/caught-by-the-tides.jpg',jinpa:'https://www.bam.org/globalassets/programs/cinema/2027fy/0926/a-pure-person-the-sonic-landscape-of-lim-giong/jinpa.jpg',kaili:'https://www.bam.org/globalassets/programs/cinema/2027fy/0926/a-pure-person-the-sonic-landscape-of-lim-giong/kaili-blues.jpg',stray:'https://metrograph.com/wp-content/uploads/2026/08/Stray-Dogs.jpeg',yiyi:'https://metrograph.imgix.net/2022/12/yiyi.jpeg?fm=pjpg&ixlib=php-3.3.1',brighter:'https://metrograph.com/wp-content/uploads/2024/02/BrighterSummerDay1-1-1600x900-c-default.jpeg',rebels:'https://metrograph.com/wp-content/uploads/2026/09/REBELS-OF-THE-NEON-GOD_2.jpeg',left:'https://metrograph.com/wp-content/uploads/2026/08/Left-Handed_Girl_u_01_42_03_05_R.jpeg',paprika:'https://metrograph.com/wp-content/uploads/2026/08/PAPRIKA_1.jpeg',ghost:'https://metrograph.imgix.net/2023/06/Ghost_in_the_Shell_1995_030.jpeg?fm=pjpg&ixlib=php-3.3.1',blade:'https://metrograph.com/wp-content/uploads/2026/08/The-Blade-copy.jpg',arsa:'https://images.amcnetworks.com/ifccenter.com/wp-content/uploads/2026/09/arsa-7.jpg',serpent:'https://images.amcnetworks.com/ifccenter.com/wp-content/uploads/2026/08/serpentspath.jpg',franz:'https://quadcinema.com/wp-content/uploads/2025/11/franz2.png',fisherman:'https://quadcinema.com/wp-content/uploads/2026/08/The-Fisherman-stills-33-1400x689.jpg',primetime:'https://www.bam.org/globalassets/programs/cinema/2027fy/0926/primetime.jpg'};
const bg=(image:string)=>({backgroundImage:`linear-gradient(180deg,rgba(5,6,8,.18),rgba(5,6,8,.78) 43%,rgba(5,6,8,.97) 84%),url("${image}")`});
function Tag({children}:{children:React.ReactNode}){return <span className="tag">{children}</span>} function TL({href,children}:{href:string;children:React.ReactNode}){return <a className="time-link" href={href} target="_blank" rel="noreferrer">{children}</a>}
type Film={title:string;year:string;region:string;director:string;type:string;venue:string;when:string;format?:string;event?:string;tags:string[];text:string;href:string;image:string};
function Card({f}:{f:Film}){return <article className="film-card image-card" style={bg(f.image)}><div className="tags">{f.tags.map(x=><Tag key={x}>{x}</Tag>)}</div><h3>{f.title}</h3><dl><div><dt>YEAR / REGION</dt><dd>{f.year} · {f.region}</dd></div><div><dt>DIRECTOR</dt><dd>{f.director}</dd></div><div><dt>TYPE</dt><dd>{f.type}</dd></div><div><dt>VENUE</dt><dd>{f.venue}</dd></div><div><dt>WHEN</dt><dd><TL href={f.href}>{f.when}</TL></dd></div>{f.format&&<div><dt>FORMAT</dt><dd>{f.format}</dd></div>}{f.event&&<div><dt>EVENT</dt><dd>{f.event}</dd></div>}</dl><p>{f.text}</p><a className="official-link" href={f.href} target="_blank" rel="noreferrer">Official listing ↗</a></article>}
const focus:Film[]=[
 {title:'Millennium Mambo / 千禧曼波',year:'2001',region:'Taiwan',director:'Hou Hsiao-hsien',type:'Urban memory film',venue:'BAM Rose Cinemas',when:'Sat Sep 19 · 5:45 PM; Wed Sep 23 · 7:00 PM',tags:['SPECIAL FOCUS','LIM GIONG'],text:'Hou’s neon Taipei drift is inseparable from Lim Giong’s electronic pulse. The composer-centered context makes sound the organizing intelligence, not decoration.',href:L.mambo,image:I.mambo},
 {title:'The Assassin / 刺客聶隱娘',year:'2015',region:'Taiwan / China / Hong Kong',director:'Hou Hsiao-hsien',type:'Wuxia',venue:'BAM Rose Cinemas',when:'Sat Sep 19 · 8:15 PM; Wed Sep 23 · 4:30 PM',format:'DCP',tags:['SPECIAL FOCUS','HOU HSIAO-HSIEN'],text:'Hou turns wuxia into an art of distance, offscreen space and moral hesitation. Its soundscape and natural-light images make this theatrical return a priority.',href:L.assassin,image:I.assassin},
 {title:'The World / 世界',year:'2004',region:'China / Japan / France',director:'Jia Zhangke',type:'Globalization drama',venue:'BAM Rose Cinemas',when:'Sun Sep 20 · 4:15 PM; Tue Sep 22 · 9:15 PM',tags:['SPECIAL FOCUS','JIA ZHANGKE'],text:'Migrant workers inhabit a Beijing theme park that promises the world while trapping them in miniature. Lim’s score and the early-digital surfaces make this essential.',href:L.world,image:I.world},
 {title:'Caught by the Tides / 風流一代',year:'2024',region:'China',director:'Jia Zhangke',type:'Archival-fiction hybrid',venue:'BAM Rose Cinemas',when:'Sun Sep 20 · 1:30 PM; Thu Sep 24 · 9:15 PM',tags:['SPECIAL FOCUS','CANNES 2024'],text:'Jia reworks footage gathered across two decades into a fractured portrait of China and a vanished relationship. Beside The World, it audits his own images.',href:L.tides,image:I.tides},
 {title:'Stray Dogs / 郊遊',year:'2013',region:'Taiwan / France',director:'Tsai Ming-liang',type:'Urban minimalist drama',venue:'Metrograph',when:'Fri Sep 18 · 6:10 PM; Sun Sep 20 · 8:45 PM',tags:['SPECIAL FOCUS','TSAI MING-LIANG'],text:'Tsai’s rain-soaked portrait of homelessness ends in one of his most punishingly patient acts of looking. Two rare repertory shows make it indispensable.',href:L.stray,image:I.stray},
 {title:'Yi Yi / 一一',year:'2000',region:'Taiwan / Japan',director:'Edward Yang',type:'Family epic',venue:'Metrograph',when:'Fri Sep 18 · 2:40 PM; Sun Sep 20 · 5:30 PM',tags:['SPECIAL FOCUS','EDWARD YANG'],text:'Yang maps a Taipei family with novelistic generosity and exact visual structure. These matinees fit neatly around BAM’s denser program.',href:L.yiyi,image:I.yiyi},
 {title:'A Brighter Summer Day / 牯嶺街少年殺人事件',year:'1991',region:'Taiwan',director:'Edward Yang',type:'Historical youth epic',venue:'Metrograph',when:'Mon Sep 21 · 3:00 PM',format:'DCP · 237 min',tags:['SPECIAL FOCUS','EDWARD YANG'],text:'Yang’s four-hour social world is the week’s most demanding single screening. Protect the afternoon; its scale warrants the commitment.',href:L.brighter,image:I.brighter},
 {title:'Rebels of the Neon God / 青少年哪吒',year:'1992',region:'Taiwan',director:'Tsai Ming-liang',type:'Urban alienation',venue:'Metrograph',when:'Thu Sep 24 · 2:10 PM',tags:['SPECIAL FOCUS','TSAI MING-LIANG'],text:'Tsai’s debut already has the flooded rooms, bruised Taipei nights and drifting bodies that define his cinema.',href:L.rebels,image:I.rebels}
];
const asian:Film[]=[
 {title:'Left-Handed Girl / 左撇子女孩',year:'2025',region:'Taiwan / France / USA',director:'Shih-Ching Tsou',type:'Family drama',venue:'Metrograph',when:'Fri Sep 18 · 6:00 PM',format:'35mm',event:'Q&A with Shih-Ching Tsou',tags:['35MM','DIRECTOR Q&A'],text:'Tsou’s solo feature brings street-level Taipei energy and a rare 35mm presentation. The filmmaker conversation makes this show materially different.',href:L.left,image:I.left},
 {title:'Kaili Blues / 路邊野餐',year:'2015',region:'China',director:'Bi Gan',type:'Dream journey',venue:'BAM Rose Cinemas',when:'Mon Sep 21 · 9:00 PM; Tue Sep 22 · 6:45 PM',tags:['ASIAN CINEMA','LONG-TAKE CINEMA'],text:'Bi Gan’s debut bends memory and geography around a hypnotic extended take. Lim Giong’s sonic presence makes the BAM context revealing.',href:L.kaili,image:I.kaili},
 {title:'Jinpa / 撞死了一只羊',year:'2018',region:'Tibet / China',director:'Pema Tseden',type:'Road fable',venue:'BAM Rose Cinemas',when:'Sun Sep 20 · 7:15 PM; Tue Sep 22 · 4:30 PM',tags:['TIBETAN CINEMA','LIM GIONG'],text:'Pema Tseden condenses revenge, chance and landscape into a compact high-altitude fable.',href:L.jinpa,image:I.jinpa},
 {title:'Paprika / パプリカ',year:'2006',region:'Japan',director:'Satoshi Kon',type:'Animated science fiction',venue:'Metrograph',when:'Sat Sep 19 · 11:45 AM',format:'35mm',tags:['35MM','ANIMATION CANON'],text:'Kon’s dream machine remains a major influence on contemporary spectacle. A single 35mm matinee is worth prioritizing.',href:L.paprika,image:I.paprika},
 {title:'Ghost in the Shell / 攻殻機動隊',year:'1995',region:'Japan',director:'Mamoru Oshii',type:'Cyberpunk animation',venue:'Metrograph',when:'Fri Sep 18 · 11:00 PM; Sun Sep 20 · 11:00 AM',format:'4K remaster',tags:['4K','CULT CANON'],text:'Oshii’s philosophical cyberpunk still sets the grammar for bodies and networks on screen. The remaster restores its nocturnal scale.',href:L.ghost,image:I.ghost},
 {title:'The Blade / 刀',year:'1995',region:'Hong Kong',director:'Tsui Hark',type:'Wuxia',venue:'Metrograph',when:'Fri Sep 18 · 8:50 PM',format:'4K restoration',tags:['4K RESTORATION','HONG KONG'],text:'Tsui shreds classical wuxia into dust, handheld violence and sensory overload. The sole restored show is a genuine event.',href:L.blade,image:I.blade}
];
const festival:Film[]=[{...focus[3],tags:['CANNES 2024 · COMPETITION']},{...asian[0],tags:['CANNES 2025 · CRITICS’ WEEK']},{title:'Franz',year:'2025',region:'Czech Republic / Germany / Poland',director:'Agnieszka Holland',type:'Kaleidoscopic biography',venue:'Quad Cinema',when:'Sep 18–24 · daily',tags:['SAN SEBASTIÁN 2025 · OFFICIAL SELECTION'],text:'Holland’s fragmented Kafka biography remains a selective current-festival inclusion and a flexible option around the one-offs.',href:L.franz,image:I.franz}];
const classics:Film[]=[focus[0],asian[3],asian[4]];
const newHits:Film[]=[
 {title:'The History of Concrete',year:'2026',region:'USA',director:'John Wilson',type:'Comic documentary',venue:'IFC Center',when:'Sep 18–24 · daily; Sep 18 & 19 guest shows',event:'John Wilson Q&As/introduction',tags:['MUBI GO','NYC OPENING'],text:'Wilson turns a failed Hallmark pitch into a sideways study of buildings, money and New York observation. The confirmed GO pick is best used on an eligible standard session.',href:L.concrete,image:I.concrete},
 {title:'Arsa',year:'2024',region:'Italy',director:'MASBEDO',type:'Island-set drama',venue:'IFC Center',when:'Sep 18–24 · daily; Fri Sep 18 · 7:00 PM Q&A sold out',event:'Q&A with MASBEDO',tags:['NEW RELEASE','ARTIST FILM'],text:'The artist duo moves into narrative cinema without losing its attention to landscape and bodies. Standard screenings remain the practical route.',href:L.arsa,image:I.arsa},festival[2]
];
const worth:Film[]=[{title:'Serpent’s Path',year:'2024',region:'France / Japan',director:'Kiyoshi Kurosawa',type:'Psychological revenge thriller',venue:'IFC Center',when:'Sep 18–24 · daily',tags:['KIYOSHI KUROSAWA','HOLDOVER'],text:'Kurosawa’s French remake of his own V-cinema nightmare remains cold, oblique and morally corrosive. Catch the holdover now.',href:L.serpent,image:I.serpent},{title:'The Fisherman',year:'2026',region:'Ghana / USA',director:'Zoey Martinson',type:'Magic-realist comedy',venue:'Quad Cinema',when:'Sep 18–24 · daily; Q&As Fri & Sat 6:45 PM',event:'Director and guest Q&As',tags:['GHANAIAN CINEMA','Q&A'],text:'A Ghana-set fishing story expands the week’s geographic range and comes with two distinct guest programs.',href:L.fisherman,image:I.fisherman},asian[5]];
const noteworthy:Film[]=[{title:'Pumping Iron',year:'1977',region:'USA',director:'George Butler & Robert Fiore',type:'Documentary',venue:'Metrograph',when:'Sat Sep 19 · 4:00 PM',format:'16mm',event:'Geof Bartz Q&A; Jeffrey Wolf moderates',tags:['16MM','CRAFT Q&A'],text:'The print and editor conversation make this more than nostalgia.',href:'https://metrograph.com/film/?vista_film_id=9999004999',image:I.concrete},{title:'Zidane: A 21st Century Portrait',year:'2006',region:'France / Iceland',director:'Douglas Gordon & Philippe Parreno',type:'Sports portrait',venue:'Metrograph',when:'Sat Sep 19 · 6:30 PM',event:'Darius Khondji Q&A',tags:['CINEMATOGRAPHER Q&A','RARE EVENT'],text:'Seventeen cameras turn a footballer into gesture, texture and sound. Khondji’s presence makes this the week’s strongest craft event.',href:'https://metrograph.com/film/?vista_film_id=9999001731',image:I.mambo},{title:'Totally F***ed Up',year:'1993',region:'USA',director:'Gregg Araki',type:'Queer New Wave',venue:'Quad Cinema',when:'Sep 22 · 8:15; Sep 23 · 8:15; Sep 24 · 6:20 PM',event:'Sep 24 introduction by Todd Verow',tags:['CULT CINEMA','INTRO'],text:'Araki’s angry, funny teen chronicle remains defining New Queer Cinema. Thursday adds living-history context.',href:L.totally,image:I.left}];
const comingFocus:Film[]=[{title:'Possible Love',year:'2026',region:'South Korea',director:'Lee Chang-dong',type:'NYFF64 drama',venue:'Film at Lincoln Center',when:'SEP 27 · 5:30 PM Q&A; SEP 28 · 11:30 AM Q&A; OCT 1 · 1:30 PM',event:'Lee Chang-dong; Sep 27 also Jeon Do-yeon, Sul Kyung-gu, Zo In-sung & Cho Yeo-jeong',tags:['SPECIAL FOCUS','SOLD OUT Q&As'],text:'Both guest sessions are sold out. Monitor only official returns; avoid resale premiums. Oct 1 is the standard fallback.',href:L.possible,image:I.concrete},{title:'Still Life / 三峡好人',year:'2006',region:'China',director:'Jia Zhangke',type:'Social-realist drama',venue:'Anthology Film Archives',when:'WITHIN SEP 18–OCT 10 PROGRAM',tags:['SPECIAL FOCUS','JIA ZHANGKE'],text:'Jia’s Three Gorges masterpiece remains on the forward radar through Anthology’s current program.',href:L.still,image:I.world}];
const comingNew:Film[]=[{title:'Primetime',year:'2026',region:'USA',director:'Lance Oppenheim',type:'Crime thriller',venue:'BAM Rose Cinemas',when:'THU SEP 24 · OPENS',tags:['A24','NEW RELEASE'],text:'Oppenheim turns the machinery of televised predation into an A24 thriller with Robert Pattinson.',href:L.primetime,image:I.primetime},{title:'The Incomer',year:'2025',region:'UK',director:'Louis Paxton',type:'Folk-horror comedy',venue:'IFC Center',when:'FRI SEP 25 · OPENS',tags:['NEW RELEASE','CULT-LEANING'],text:'A remote-island comedy with folk-horror edges fits the guide’s cult appetite; later showtimes are not yet inferred.',href:L.incomer,image:I.blade}];
const events=[
 ['SEP 18 · 4:40, 7:15 & 9:45 PM; SEP 19 · 4:40 PM','The History of Concrete — John Wilson events',L.concrete,'IFC · Q&As after Sep 18 4:40 and 7:15, extended intro at 9:45; Sep 19 Q&A after 4:40. Rachel Kaly moderates Sep 18 at 7:15.'],
 ['SEP 18 · 6:00 PM','Left-Handed Girl — Shih-Ching Tsou Q&A',L.left,'Metrograph · 35mm. High priority; buy now if seats remain.'],['SEP 18 · 7:00 PM','Arsa — MASBEDO Q&A',L.arsa,'IFC · sold out; monitor official returns only.'],
 ['SEP 18 · 6:45 PM; SEP 19 · 6:45 PM','The Fisherman — Zoey Martinson Q&As',L.fisherman,'Quad · Fri with Michael Ansong-Dwamena and Anna Agbotse; Sat with Yvonne Orji, Wawa Gatheru and Walla Elsheikh.'],
 ['SEP 19 · 4:00 PM','Pumping Iron — Geof Bartz Q&A','https://metrograph.com/film/?vista_film_id=9999004999','Metrograph · 16mm; moderated by Jeffrey Wolf, ACE.'],['SEP 19 · 6:30 PM','Zidane — Darius Khondji Q&A','https://metrograph.com/film/?vista_film_id=9999001731','Metrograph · rare cinematographer conversation; buy now.'],
 ['SEP 19 · 6:30 PM','Knife — Andy Grieve Q&A','https://www.ifccenter.com/films/knife-the-attempted-murder-of-salman-rushdie/','IFC · editor Andy Grieve in conversation, moderated by Alec Baldwin.'],
 ['SEP 19 · 6:20 & 8:30 PM','Checkout — Jonathan Dekel Q&As',L.checkout,'Quad · 6:20 Dekel; 8:30 Dekel and actor Josh Pais.'],['SEP 21 · 7:30 PM','Critics & Filmmakers — Godfrey Cheshire and Alex Winter','https://www.ifccenter.com/films/critics-filmmakers-godfrey-cheshire-and-alex-winter/','IFC · conversation; tickets listed.'],
 ['SEP 24 · 7:45 PM','The Scout — Paula González-Nasser and Mimi Davila Q&A',L.scout,'Film Forum · sneak preview with director and actor.'],['SEP 26 · 7:50 PM','Eddington — Ari Aster and Darius Khondji Q&A',L.eddington,'Metrograph · sold out; monitor official returns only.'],
 ['SEP 27 · 5:30 PM; SEP 28 · 11:30 AM','Possible Love — Lee Chang-dong Q&As',L.possible,'NYFF64 · both guest sessions sold out; Sep 27 also lists Jeon Do-yeon, Sul Kyung-gu, Zo In-sung and Cho Yeo-jeong.'],['SEP 30 · see official page','You Can See Everything — Nathan Fielder and Lance Oppenheim',L.fielder,'NYFF64 · New York premiere with both filmmakers.'],['OCT 1 · 9:15 PM','Cameron Winter at Carnegie Hall — Paul Thomas Anderson in person',L.cameron,'NYFF64 · 35mm world premiere with Anderson and Cameron Winter.'],['OCT 3 · 1:30 PM','Amos Vogel Lecture — Ryūsuke Hamaguchi',L.hamaguchi,'NYFF64 · Hamaguchi at Walter Reade.'],['OCT 6','The Third Eye — Olivia Harrison with Martin Scorsese',L.scorsese,'BAM · book-and-images conversation; tickets on sale.']
];
const M=(id:string)=>`https://metrograph.com/film/?vista_film_id=${id}`;
export default function Home(){const picks=[focus[1],focus[2],focus[4],focus[0],focus[3],asian[0],asian[1],asian[2],asian[3],asian[4],asian[5],newHits[0]];return <main>
 <header className="mast"><a className="brand" href="#top"><span className="brand-reel">●</span> NYC / ARTHOUSE <span className="brand-film">35MM</span></a><nav aria-label="Primary navigation"><a href="#picks">This Week</a><a href="#alerts">Tickets</a><a href="#nyff">NYFF64</a><a href="#special">Special Focus</a><a href="#asian">Asian</a><a href="#festival">Festival</a><a href="#all-other">All Other</a><a href="#soon">Coming Soon</a><a href="#events">Events</a><a href="#archive">Archive</a></nav></header>
 <section className="hero" id="top"><div className="hero-rotator" aria-hidden="true"><span style={{backgroundImage:`url("${I.assassin}")`}}/><span style={{backgroundImage:`url("${I.world}")`}}/><span style={{backgroundImage:`url("${I.stray}")`}}/></div><div className="hero-shade"/><div className="eyebrow hero-content"><span>✦ WEEK 07</span><span>NOW SHOWING · NEW YORK</span></div><div className="hero-title-wrap hero-content"><span className="projector-mark">◉</span><h1>NYC Arthouse<br/><em>Film Guide</em></h1><span className="film-strip">▯ ▯ ▯ ▯ ▯ ▯</span></div><div className="hero-foot hero-content"><p className="range">SEP 18 → SEP 24 <sup>2026</sup></p><p className="dek">A personal weekly map of repertory, international and independent cinema—weighted toward Asian cinema, rare prints, formal risk and filmmaker appearances.</p></div></section>
 <section className="three"><div><p className="kicker">🎟 IF I COULD ONLY SEE THREE</p></div><ol><li><b>THE ASSASSIN</b><span>Hou · sound and space</span></li><li><b>THE WORLD</b><span>Jia · globalization in miniature</span></li><li><b>STRAY DOGS</b><span>Tsai · rare theatrical return</span></li></ol></section>
 <section className="section" id="picks"><div className="section-head"><p className="kicker">🎬 THIS WEEK</p><h2>Top picks</h2><p>BAM’s Lim Giong retrospective concentrates Hou and Jia while Metrograph answers with Tsai, Edward Yang, 35mm anime and restored Hong Kong cinema.</p></div><div className="pick-list">{picks.map((p,i)=><article className="pick image-pick" style={bg(p.image)} key={p.title}><div className="rank">{String(i+1).padStart(2,'0')}</div><div className="pick-main"><div className="tags">{p.tags.map(t=><Tag key={t}>{t}</Tag>)}</div><h3>{p.title}</h3><p>{p.text}</p></div><div className="showtime"><b>{p.when}</b><span>{p.venue}</span><a href={p.href} target="_blank" rel="noreferrer">Official listing ↗</a></div></article>)}</div></section>
 <section className="mubi-band image-band" style={bg(I.concrete)}><div><p className="kicker">🎫 MUBI GO THIS WEEK</p><h2>The History of Concrete</h2></div><div className="mubi-copy"><p><b>Eligibility: Fri Sep 18–Thu Sep 24</b></p><p>MUBI’s live US GO page explicitly names John Wilson’s documentary as the film of the week. IFC is the confirmed NYC engagement; verify the exact eligible session in the app because special-event shows may be excluded.</p><p><b>Worth using:</b> yes—prefer a standard session and save cash for rarer repertory.</p><a className="arrow" href={L.mubi} target="_blank" rel="noreferrer">Live MUBI GO offer ↗</a></div></section>
 <section className="section ruled" id="alerts"><div className="section-head"><p className="kicker">🎟 PRIORITY TICKET ALERTS</p><h2>Act before guest shows disappear</h2></div><div className="mini-grid"><article><Tag>BUY NOW</Tag><h3><a href={L.left} target="_blank" rel="noreferrer">Left-Handed Girl — 35mm + Shih-Ching Tsou</a></h3><p>Fri Sep 18 · 6:00 PM · Metrograph. Direct filmmaker event and recent Cannes title.</p></article><article><Tag>BUY NOW</Tag><h3><a href={M('9999001731')} target="_blank" rel="noreferrer">Zidane — Darius Khondji Q&A</a></h3><p>Sat Sep 19 · 6:30 PM · Metrograph. Rare cinematography conversation.</p></article><article><Tag>MONITOR RETURNS</Tag><h3><a href={L.possible} target="_blank" rel="noreferrer">Possible Love — Lee Chang-dong Q&As</a></h3><p>Sep 27 & 28 · NYFF64. Both Q&As are sold out; use only official returns.</p></article></div></section>
 <section className="section dark" id="nyff"><div className="section-head"><p className="kicker">🎟 NYFF64 — WHAT TO PRIORITIZE</p><h2>Festival strategy after public on-sale</h2><p>Single tickets opened Sep 15 at noon ET. Inventory is live and volatile: use official availability, avoid resale premiums, and replace a regular ticket only after securing the preferred Q&A.</p></div><div className="mini-grid"><article><Tag>MUST SEE / BUY EARLY</Tag><h3>Possible Love · All of a Sudden · Rose · Fatherland · Fyord</h3><p>Protect guest-bearing or festival-only sessions first. Possible Love’s Q&As are already sold out.</p></article><article><Tag>FESTIVAL-ONLY PRIORITY</Tag><h3>The Day She Returns · NAZA · No Way to Lay My Eyes</h3><p>Favor titles least likely to receive a normal NYC run. Either format works for Everytime.</p></article><article><Tag>Q&A UPGRADE</Tag><h3>Lee Chang-dong · Ryūsuke Hamaguchi · Paul Thomas Anderson</h3><p>Prioritize confirmed appearances over duplicate standard screenings. <a href={L.nyff} target="_blank" rel="noreferrer">Official NYFF64 hub ↗</a></p></article></div></section>
 <section className="alert"><span>🎼 PROGRAM OF THE WEEK</span><p><b>A Pure Person: The Sonic Landscape of Lim Giong</b> runs Sep 18–24 at BAM, joining Hou Hsiao-hsien, Jia Zhangke, Bi Gan and Pema Tseden through a composer who reshaped modern Asian cinema. <a href={L.pure} target="_blank" rel="noreferrer">Full program ↗</a></p></section>
 {[["special","01 / 🎯 SPECIAL FOCUS","Hou, Jia, Tsai and Edward Yang",focus],["asian","02 / 🌏 ASIAN CINEMA","Taiwan, China, Tibet, Japan and Hong Kong",asian],["festival","🏆 FESTIVAL","Recent festival discoveries",festival],["classics","04 / 🎞 ALL-TIME CLASSICS","Modern canon in presentations that matter",classics],["new","05 / 🆕 NEW HITS","Current openings and holds",newHits],["worth","06 / ⭐ WORTH SEEING","Strong alternatives",worth],["noteworthy","07 / 🎥 OTHER NOTEWORTHY SCREENINGS","Craft, context and cult history",noteworthy]].map((s,i)=><section className={`section ${i%2===0?'dark':''}`} id={s[0] as string} key={s[0] as string}><div className="section-head"><p className="kicker">{s[1] as string}</p><h2>{s[2] as string}</h2>{s[0]==='special'&&<p>Eight direct matches; no Nuri Bilge Ceylan NYC screening was confirmed in the 90-day watch.</p>}</div><div className="card-grid">{(s[3] as Film[]).map((f,j)=><Card key={f.title+j} f={f}/>)}</div></section>)}
 <section className="section schedule dark" id="all-other"><div className="section-head"><p className="kicker">08 / 📋 ALL OTHER SCREENINGS</p><h2>The rest of the map</h2><p>Seven complete days from the venue sweep; featured films are excluded and every time links to a title-specific official page.</p></div><div className="schedule-grid">
  <div><h3>FRI SEP 18</h3><p>Metrograph — Chungking Express <TL href={M('9999000735')}>12:30 PM</TL>; Clash of the Titans 35mm <TL href={M('9999004983')}>12:45 PM</TL>; Evita 35mm <TL href={M('9999001730')}>3:15 PM</TL>; The Witch Hunt <TL href={M('9999004995')}>9:00 PM</TL>; Knock Off 35mm <TL href={M('9999002763')}>11:00 PM</TL>. IFC — Sundance Short Film Tour <TL href="https://www.ifccenter.com/films/2026-sundance-film-festival-short-film-tour/">12:50 &amp; 7:35 PM</TL>; The Kingdom <TL href="https://www.ifccenter.com/films/the-kingdom/">4:20 &amp; 9:05 PM</TL>; Angel’s Egg <TL href="https://www.ifccenter.com/films/angels-egg/">11:35 PM</TL>.</p></div>
  <div><h3>SAT SEP 19</h3><p>Metrograph — Oedipus Rex <TL href={M('9999002042')}>12:15 PM</TL>; Zu <TL href={M('9999001262')}>1:50 PM</TL>; Notes Toward African Orestes <TL href={M('9999004998')}>2:30 PM</TL>; Games of Love and Loneliness <TL href={M('9999004988')}>4:00 PM</TL>; Stealing Beauty 35mm <TL href={M('9999003314')}>8:15 PM</TL>; The Warriors 35mm <TL href={M('9999002970')}>10:50 PM</TL>. IFC — Knife + Andy Grieve Q&amp;A, Alec Baldwin moderates <TL href="https://www.ifccenter.com/films/knife-the-attempted-murder-of-salman-rushdie/">6:30 PM</TL>; The Kingdom <TL href="https://www.ifccenter.com/films/the-kingdom/">4:20 &amp; 9:50 PM</TL>.</p></div>
  <div><h3>SUN SEP 20</h3><p>Metrograph — Knock Off 35mm <TL href={M('9999002763')}>1:00 PM</TL>; Wives <TL href={M('9999004985')}>3:00 PM</TL>; Time and Tide 35mm <TL href={M('9999003587')}>3:10 PM</TL>. IFC — The Kingdom <TL href="https://www.ifccenter.com/films/the-kingdom/">4:20 &amp; 9:05 PM</TL>; Knife <TL href="https://www.ifccenter.com/films/knife-the-attempted-murder-of-salman-rushdie/">1:45, 6:30 &amp; 9:20 PM</TL>; Sundance Short Film Tour <TL href="https://www.ifccenter.com/films/2026-sundance-film-festival-short-film-tour/">7:35 PM</TL>.</p></div>
  <div><h3>MON SEP 21</h3><p>Metrograph — Jason and the Argonauts 35mm <TL href={M('9999002021')}>3:00 PM</TL>; Days and Nights in the Forest 4K <TL href={M('9999004969')}>5:15 PM</TL>; Women on the Verge 35mm <TL href={M('9999003126')}>7:30 PM</TL>; Peking Opera Blues 4K <TL href={M('9999004982')}>7:35 PM</TL>; Uncut Gems 35mm <TL href={M('9999002255')}>9:30 PM</TL>; Delicatessen 4K <TL href={M('9999001727')}>9:45 PM</TL>. IFC — Sundance Short Film Tour <TL href="https://www.ifccenter.com/films/2026-sundance-film-festival-short-film-tour/">12:30 PM</TL>; The Kingdom <TL href="https://www.ifccenter.com/films/the-kingdom/">4:20 &amp; 9:05 PM</TL>.</p></div>
  <div><h3>TUE SEP 22</h3><p>Metrograph — Petite Maman <TL href={M('9999004050')}>2:00 PM</TL>; La Haine <TL href={M('9999003673')}>2:15 PM</TL>; L’Argent <TL href={M('9999004934')}>3:40 PM</TL>; Orpheus 35mm <TL href={M('9999001996')}>4:20 PM</TL>; Wake in Fright 4K <TL href={M('9999004939')}>5:30 PM</TL>; City of Lost Children 35mm <TL href={M('9999001728')}>7:40 PM</TL>; Office Space 35mm <TL href={M('9999003559')}>10:00 PM</TL>. IFC — Steal This Story, Please! <TL href="https://www.ifccenter.com/films/steal-this-story-please/">7:00 PM</TL>; The Kingdom <TL href="https://www.ifccenter.com/films/the-kingdom/">4:20 &amp; 9:05 PM</TL>.</p></div>
  <div><h3>WED SEP 23</h3><p>Metrograph — Happy Together <TL href={M('9999000497')}>2:00 PM</TL>; Shanghai Blues 4K <TL href={M('9999001446')}>2:30 PM</TL>; American Job <TL href={M('9999004981')}>4:00 PM</TL>; Black Orpheus 35mm <TL href={M('9999004990')}>4:40 PM</TL>; The Apartment 35mm <TL href={M('9999000609')}>7:00 PM</TL>; I Hired a Contract Killer <TL href={M('9999001903')}>8:15 PM</TL>; The Night Is Short, Walk on Girl <TL href={M('9999001554')}>9:35 PM</TL>. IFC — Take Me Home <TL href="https://www.ifccenter.com/films/take-me-home/">2:25, 4:25 &amp; 6:50 PM</TL>; The Kingdom <TL href="https://www.ifccenter.com/films/the-kingdom/">9:05 PM</TL>.</p></div>
  <div><h3>THU SEP 24</h3><p>Metrograph — Clash of the Titans 35mm <TL href={M('9999004983')}>2:00 PM</TL>; La Notte <TL href={M('9999004957')}>4:20 PM</TL>; Playtime <TL href={M('9999001700')}>4:25 PM</TL>; Troy 35mm <TL href={M('9999004984')}>6:50 PM</TL>; Brazil 4K <TL href={M('9999000356')}>7:00 PM</TL>; True Romance <TL href={M('9999003371')}>9:50 PM</TL>; Eve’s Bayou <TL href={M('9999001795')}>10:00 PM</TL>. IFC — Take Me Home <TL href="https://www.ifccenter.com/films/take-me-home/">2:25, 4:25 &amp; 6:50 PM</TL>; The Kingdom <TL href="https://www.ifccenter.com/films/the-kingdom/">9:05 PM</TL>.</p></div>
 </div></section>
 <section className="section soon" id="soon"><div className="section-head"><p className="kicker">09 / 🔭 COMING SOON — SPECIAL FOCUS</p><h2>Direct matches in the decision window</h2></div><div className="card-grid">{comingFocus.map(f=><Card key={f.title} f={f}/>)}</div></section>
 <section className="section soon dark" id="new-releases"><div className="section-head"><p className="kicker">10 / 🔭 COMING SOON — NEW RELEASES</p><h2>High-fit theatrical openings</h2></div><div className="card-grid">{comingNew.map(f=><Card key={f.title} f={f}/>)}</div></section>
 <section className="section events" id="events"><div className="section-head"><p className="kicker">11 / 🎤 NYC FILM EVENTS</p><h2>30-day event radar</h2><p>Guest-bearing dates, participants and supported ticket status.</p></div><div className="event-list">{events.map(e=><div key={e[0]+e[1]}><time>{e[0]}</time><h3><a href={e[2]} target="_blank" rel="noreferrer">{e[1]}</a></h3><p>{e[3]}</p></div>)}</div></section>
 <section className="section" id="calendar"><div className="section-head"><p className="kicker">📅 30-DAY EVENT CALENDAR</p><h2>At a glance</h2></div><div className="mini-grid"><article><Tag>SEP 18–24</Tag><h3>Immediate priorities</h3><p>Tsou, John Wilson, MASBEDO, Khondji, Bartz, Martinson and the Lim Giong series.</p></article><article><Tag>SEP 25–OCT 3</Tag><h3>NYFF64 peak</h3><p>Lee Chang-dong, Ari Aster, Nathan Fielder, Lance Oppenheim, Paul Thomas Anderson and Ryūsuke Hamaguchi.</p></article><article><Tag>OCT 4–17</Tag><h3>Next wave</h3><p>Scorsese at BAM and later NYFF/BAM programs; inventory should be rechecked weekly.</p></article></div></section>
 <section className="section" id="archive"><div className="section-head"><p className="kicker">🗃 PREVIOUS WEEKS / ARCHIVE</p><h2>Rolling 10-week archive</h2></div><div className="mini-grid">{[['06','Sep 11–17','Dust in the Wind, Rebels of the Neon God and A Brighter Summer Day.'],['05','Sep 4–10','Daughter of the Nile, Solaris and A Brighter Summer Day.'],['04','Aug 28–Sep 3','Goodbye, Dragon Inn, Nostalghia and Mulholland Drive.'],['03','Aug 21–27','Memoria, Happy Hour, Stalker and BAM’s Arthouse Sci-Fi.'],['02','Aug 14–20','Ōshima, Irréversible, 2001 in 70mm and Ozu.'],['01','Aug 8–14','The Hole, Late Fame, Millennium Mambo and Center Stage.']].map(a=><article key={a[0]}><Tag>WEEK {a[0]}</Tag><h3>{a[1]}, 2026</h3><p>{a[2]}</p><a href={`/chrisfilmguide/archive/week-${a[0]}/`}>Open archived edition ↗</a></article>)}</div></section>
 <footer><p><b>IF I COULD ONLY SEE THREE:</b> The Assassin · The World · Stray Dogs</p><p>Verified against official listings on Sep 18, 2026. Recheck before travel.</p></footer>
 </main>}
