const L={
mubi:'https://mubi.com/en/us/go',nyff:'https://www.filmlinc.org/nyff/nyff64-lineup/',
overt:'https://www.filmlinc.org/nyff2026/films/overt-listening/',fjord:'https://www.filmlinc.org/nyff2026/films/fjord/',returns:'https://www.filmlinc.org/nyff2026/films/the-day-she-returns/',nowhere:'https://www.filmlinc.org/nyff2026/films/nowhere-to-lay-my-eyes/',everytime:'https://www.filmlinc.org/nyff2026/films/everytime/',fatherland:'https://www.filmlinc.org/nyff2026/films/fatherland/',
sandwich:'https://metrograph.com/film/?vista_film_id=9999004987',stray:'https://metrograph.com/film/?vista_film_id=9999004997',yii:'https://metrograph.com/film/?vista_film_id=9999001293',dust:'https://metrograph.com/film/?vista_film_id=9999003943',brighter:'https://metrograph.com/film/?vista_film_id=9999002246',sympathy:'https://metrograph.com/film/?vista_film_id=9999004610',paprika:'https://metrograph.com/film/?vista_film_id=9999002029',ulysses:'https://metrograph.com/film/?vista_film_id=9999005023',
begotten:'https://www.ifccenter.com/films/begotten/',naza:'https://www.ifccenter.com/films/naza/',peltier:'https://www.ifccenter.com/films/free-leonard-peltier/',concrete:'https://www.ifccenter.com/films/the-history-of-concrete/',devils:'https://www.ifccenter.com/films/the-devils/',lily:'https://www.ifccenter.com/films/all-about-lily-chou-chou/',
bamNyff:'https://www.filmlinc.org/nyff2026/daily/announcing-nyff64-screenings-at-bam-momi-alamo-drafthouse-staten-island-and-bronxs-amc-bay-plaza/',moma:'https://www.moma.org/calendar/film/',underground:'https://www.moma.org/calendar/film/5931',anthology:'https://www.anthologyfilmarchives.org/film_screenings/series'};
const I={
overt:'https://wp.filmlinc.org/wp-content/uploads/2026/08/Overt-Listening_NYFF64_01.jpeg',fjord:'https://wp.filmlinc.org/wp-content/uploads/2026/08/FJORD_NYFF64_01-scaled.webp',returns:'https://wp.filmlinc.org/wp-content/uploads/2026/07/The-Day-She-Returns_NYFF64_01.jpeg',nowhere:'https://wp.filmlinc.org/wp-content/uploads/2026/07/Nowhere-to-Lay-My-Eyes_NYFF64_01.jpg',everytime:'https://wp.filmlinc.org/wp-content/uploads/2026/08/Everytime_NYFF64_02-scaled.jpg',
sandwich:'https://metrograph.com/wp-content/uploads/2026/08/The-Sandwich-Man.jpeg',stray:'https://metrograph.com/wp-content/uploads/2026/08/Stray-Dogs.jpeg',yii:'https://images.mubicdn.net/images/film/725/cache-8377-1745489510/image-w1280.jpg',dust:'https://metrograph.com/wp-content/uploads/2025/11/DUST-IN-THE-WIND.jpg',brighter:'https://images.mubicdn.net/images/film/693/cache-8304-1745489507/image-w1280.jpg',sympathy:'https://metrograph.com/wp-content/uploads/2026/09/Mr-Vengeance-01.jpeg',paprika:'https://images.mubicdn.net/images/film/3118/cache-9913-1745489569/image-w1280.jpg',ulysses:'https://metrograph.com/wp-content/uploads/2026/09/Ulysses-Gaze.jpeg',
begotten:'https://images.amcnetworks.com/ifccenter.com/wp-content/uploads/2026/09/begotten-10.jpg',naza:'https://wp.filmlinc.org/wp-content/uploads/2026/07/NAZA_NYFF64_01.jpg',concrete:'https://images.mubicdn.net/images/film/461757/cache-1154970-1790414868/image-w1280.jpg',peltier:'https://images.amcnetworks.com/ifccenter.com/wp-content/uploads/2026/09/freeleonardp-1.jpg',devils:'https://images.amcnetworks.com/ifccenter.com/wp-content/uploads/2026/08/the-devils2.jpg',lily:'https://images.amcnetworks.com/ifccenter.com/wp-content/uploads/2026/09/lilychouchou.jpg'};
const bg=(image:string)=>({backgroundImage:'linear-gradient(180deg,rgba(5,6,8,.18),rgba(5,6,8,.78) 43%,rgba(5,6,8,.97) 84%),url("'+image+'")'});
function Tag({children}:{children:React.ReactNode}){return <span className="tag">{children}</span>}
function TL({href,children}:{href:string;children:React.ReactNode}){return <a className="time-link" href={href} target="_blank" rel="noreferrer">{children}</a>}
type Film={title:string;year:string;region:string;director:string;type:string;venue:string;when:string;format?:string;event?:string;tags:string[];text:string;href:string;image:string};
function Card({f}:{f:Film}){return <article className="film-card image-card" style={bg(f.image)}><div className="tags">{f.tags.map(x=><Tag key={x}>{x}</Tag>)}</div><h3>{f.title}</h3><dl><div><dt>YEAR / REGION</dt><dd>{f.year} · {f.region}</dd></div><div><dt>DIRECTOR</dt><dd>{f.director}</dd></div><div><dt>TYPE</dt><dd>{f.type}</dd></div><div><dt>VENUE</dt><dd>{f.venue}</dd></div><div><dt>WHEN</dt><dd><TL href={f.href}>{f.when}</TL></dd></div>{f.format&&<div><dt>FORMAT</dt><dd>{f.format}</dd></div>}{f.event&&<div><dt>EVENT</dt><dd>{f.event}</dd></div>}</dl><p>{f.text}</p><a className="official-link" href={f.href} target="_blank" rel="noreferrer">Official listing ↗</a></article>}
const M=(id:string)=>'https://metrograph.com/film/?vista_film_id='+id;
const overt:Film={title:'Overt Listening',year:'2026',region:'U.S. / Austria / Germany',director:'Tiffany Sia',type:'NYFF64 Currents · World Premiere',venue:'Film at Lincoln Center',when:'Sat Oct 3 · 12:00 PM; Sun Oct 4 · 2:45 PM',event:'Q&A with Tiffany Sia after both screenings',tags:['WORLD PREMIERE','DIRECTOR Q&A','TAIWAN / HONG KONG'],text:'Sia turns Kinmen’s Cold War landscape into a mostly wordless study of sound as political force. Keep the Saturday screening already held: it is more singular than the conflicting Hamaguchi lecture and includes the full Q&A.',href:L.overt,image:I.overt};
const sandwich:Film={title:'The Sandwich Man / 兒子的大玩偶',year:'1983',region:'Taiwan',director:'Hou Hsiao-hsien, Tseng Chuang-hsiang & Wan Jen',type:'Taiwan New Cinema anthology',venue:'Metrograph',when:'Mon Oct 5 · 6:00 PM',format:'DCP · 105 min',tags:['SPECIAL FOCUS','HOU HSIAO-HSIEN','RARE SCREENING'],text:'Hou’s segment helped announce Taiwan New Cinema’s humane realism. This single weekday show is the week’s rarest direct-focus repertory match.',href:L.sandwich,image:I.sandwich};
const fjord:Film={title:'Fjord',year:'2026',region:'Romania / France / Norway / Sweden / Denmark',director:'Cristian Mungiu',type:'Social drama · NYFF64 Spotlight',venue:'Film at Lincoln Center',when:'Sun Oct 4 · 8:45 PM; Mon Oct 5 · 5:00 PM',event:'Q&A with Cristian Mungiu & Sebastian Stan after both screenings',tags:['CANNES 2026 · COMPETITION','PALME D’OR','DIRECTOR Q&A','NEON'],text:'Mungiu’s second Palme d’Or makes this the highest-value remaining NYFF guest event. Pay only for the Q&A upgrade—not a resale premium—because it opens Oct 9.',href:L.fjord,image:I.fjord};
const nowhere:Film={title:'Nowhere to Lay My Eyes / 눈둘데가 없네',year:'2026',region:'South Korea',director:'Hong Sangsoo',type:'Family drama · NYFF64 Main Slate',venue:'Film at Lincoln Center',when:'Wed Oct 7 · 8:45 PM',tags:['SPECIAL FOCUS','LOCARNO 2026 · COMPETITION','BEST DIRECTOR'],text:'Hong’s Jeju-set family miniature won Locarno prizes for direction and Kim Min-hee. Choose it for direct-focus value and scarcity rather than event value.',href:L.nowhere,image:I.nowhere};
const returns:Film={title:'The Day She Returns / 그녀가 돌아온 날',year:'2026',region:'South Korea',director:'Hong Sangsoo',type:'NYFF64 Main Slate',venue:'Film at Lincoln Center',when:'Tue Oct 6 · 9:00 PM; Thu Oct 8 · 6:15 PM',tags:['SPECIAL FOCUS','BERLINALE 2026 · PANORAMA'],text:'This three-conversation portrait remains the explicit festival-experience priority. Cinema Guild will release it later, but the NYFF context is worth preserving.',href:L.returns,image:I.returns};
const everytime:Film={title:'Everytime',year:'2026',region:'Germany / Austria',director:'Sandra Wollner',type:'Grief drama · NYFF64 Main Slate',venue:'BAM / Film at Lincoln Center',when:'Sat Oct 3 · 4:30 PM BAM; Tue Oct 6 · 3:30 PM; Thu Oct 8 · 12:30 PM',tags:['CANNES 2026 · UN CERTAIN REGARD','SECTION WINNER'],text:'Wollner’s reality-bending grief film is one of the flexible-format festival discoveries. Weekday FLC slots avoid Saturday’s Overt Listening priority.',href:L.everytime,image:I.everytime};
const stray:Film={title:'Stray Dogs / 郊遊',year:'2013',region:'Taiwan / France',director:'Tsai Ming-liang',type:'Slow-cinema drama',venue:'Metrograph',when:'Tue Oct 6 · 7:00 PM',tags:['SPECIAL FOCUS','TSAI MING-LIANG'],text:'Tsai’s rain-soaked portrait of precarity is a monumental large-screen experience. It conflicts with the sold-out 6:15 PM Fjord preview.',href:L.stray,image:I.stray};
const yii:Film={title:'Yi Yi / 一一',year:'2000',region:'Taiwan / Japan',director:'Edward Yang',type:'Family epic',venue:'Metrograph',when:'Tue Oct 6 · 3:40 PM',format:'DCP · 173 min',tags:['SPECIAL FOCUS','ASIAN CANON'],text:'Yang’s panoramic family drama is inexhaustible, though less rare than the Hou and Hong options. It pairs cleanly with Stray Dogs.',href:L.yii,image:I.yii};
const dust:Film={title:'Dust in the Wind / 戀戀風塵',year:'1986',region:'Taiwan',director:'Hou Hsiao-hsien',type:'Coming-of-age drama',venue:'Metrograph',when:'Wed Oct 7 · 3:30 PM',tags:['SPECIAL FOCUS','HOU HSIAO-HSIEN'],text:'Hou’s railway rhythms and offscreen history make this canonical Taiwan New Cinema. Pair it with Nowhere to Lay My Eyes.',href:L.dust,image:I.dust};
const brighter:Film={title:'A Brighter Summer Day / 牯嶺街少年殺人事件',year:'1991',region:'Taiwan',director:'Edward Yang',type:'Historical youth epic',venue:'Metrograph',when:'Wed Oct 7 · 6:00 PM',format:'DCP · 237 min',tags:['SPECIAL FOCUS','EDWARD YANG'],text:'Yang’s four-hour masterpiece overlaps with Nowhere to Lay My Eyes. Choose Hong if this classic is already familiar theatrically.',href:L.brighter,image:I.brighter};
const sympathy:Film={title:'Sympathy for Mr. Vengeance / 복수는 나의 것',year:'2002',region:'South Korea',director:'Park Chan-wook',type:'Revenge tragedy',venue:'Metrograph',when:'Sat Oct 3 · 4:45 PM; Thu Oct 8 · 9:45 PM',format:'35mm',event:'Oct 3 intro by LEENALCHI + Q&A with composer Jang Young Gyu, moderated by Goran Topalovic',tags:['35MM','COMPOSER Q&A','KOREAN CULT CANON'],text:'The Saturday guest show is a true upgrade but collides with Everytime after Overt Listening. Thursday retains 35mm without the conversation.',href:L.sympathy,image:I.sympathy};
const paprika:Film={title:'Paprika / パプリカ',year:'2006',region:'Japan',director:'Satoshi Kon',type:'Animated science fiction',venue:'Metrograph',when:'Fri Oct 2 · 1:45 PM; Mon Oct 5 · 10:25 PM; Thu Oct 8 · 7:45 PM',format:'35mm',tags:['35MM','ANIMATION CANON'],text:'Kon’s dream-machine remains foundational to contemporary spectacle. Thursday is cleanest if Hong is taken Tuesday.',href:L.paprika,image:I.paprika};
const begotten:Film={title:'Begotten',year:'1989',region:'USA',director:'E. Elias Merhige',type:'Experimental horror',venue:'IFC Center',when:'Oct 2–8 · daily',format:'4K restoration',tags:['4K RESTORATION','TRANSGRESSIVE','CULT CANON'],text:'The Q&A has passed, but the restoration keeps Merhige’s handmade nightmare among the week’s most formally radical options.',href:L.begotten,image:I.begotten};
const naza:Film={title:'NAZA',year:'2026',region:'Israel / Palestine',director:'Yuval Abraham & Rachel Szor',type:'Investigative documentary',venue:'IFC Center',when:'Oct 2–8 · daily',format:'DCP · 80 min',tags:['NEW RELEASE','NYFF64'],text:'The No Other Land collaborators examine systems behind the mass killing of Palestinian civilians in Gaza. The IFC run removes festival-ticket pressure.',href:L.naza,image:I.naza};
const concrete:Film={title:'The History of Concrete',year:'2026',region:'USA',director:'John Wilson',type:'Essay documentary / comedy',venue:'IFC Center',when:'Oct 2–8 · daily',format:'DCP · 101 min',tags:['NEW RELEASE','NYC ESSAY FILM'],text:'Wilson expands his sidewalk curiosity into a feature-length history of concrete and American oddity. Fit its plentiful times around rarer commitments.',href:L.concrete,image:I.concrete};
const peltier:Film={title:'Free Leonard Peltier',year:'2026',region:'USA',director:'Jesse Short Bull & David France',type:'Documentary',venue:'IFC Center',when:'Fri Oct 2 & Sat Oct 3 · 6:30 PM; Sun Oct 4 · 1:15 PM',event:'Q&A with both directors after each listed show',tags:['DIRECTOR Q&A','NEW RELEASE'],text:'The directors revisit Peltier’s disputed conviction with direct access and legal context. Buy only if a guest show fits around NYFF.',href:L.peltier,image:I.peltier};
const ulysses:Film={title:'Ulysses’ Gaze',year:'1995',region:'Greece / Balkans',director:'Theo Angelopoulos',type:'Historical road epic',venue:'Metrograph',when:'Sun Oct 4 · 6:10 PM; Thu Oct 8 · 4:20 PM',format:'35mm · 176 min',tags:['35MM','RARE REPERTORY'],text:'Angelopoulos’s searching Balkan odyssey is a rare print booking. Sunday conflicts with Fjord’s Q&A; Thursday is better.',href:L.ulysses,image:'https://metrograph.com/wp-content/uploads/2026/09/Ulysses.jpg'};
const focus=[sandwich,stray,yii,dust,brighter,nowhere,returns];
const asian=[overt,sandwich,stray,yii,dust,brighter,sympathy,paprika];
const festival=[fjord,everytime,returns,nowhere,naza];
const classics=[brighter,yii,sympathy,paprika];
const newHits=[naza,concrete];
const worth=[overt,fjord,peltier];
const noteworthy=[begotten,ulysses,{title:'Long Live the Underground! — closing programs',year:'1950s–2020s',region:'USA',director:'Various',type:'Experimental cinema series',venue:'MoMA',when:'Sat Oct 3–Thu Oct 8 · selected programs',format:'Multiple formats',tags:['EXPERIMENTAL','FILM-MAKERS’ COOP'],text:'The final week of MoMA’s Film-Makers’ Cooperative and Millennium Film Workshop survey protects a radical lineage.',href:L.underground,image:I.begotten}];
const picks=[overt,sandwich,fjord,nowhere,returns,everytime,stray,sympathy,brighter,dust,paprika,begotten];
const events=[
['OCT 2 & 3 · 6:30 PM; OCT 4 · 1:15 PM','Free Leonard Peltier — Jesse Short Bull & David France Q&As',L.peltier,'IFC · buy only for a guest-bearing show.'],
['OCT 3 · 12:00 PM; OCT 4 · 2:45 PM','Overt Listening — Tiffany Sia Q&As',L.overt,'NYFF64 · keep Saturday; it conflicts with the Hamaguchi lecture.'],
['OCT 3 · 2:30 PM','The Taking of Pelham One Two Three — introduction and book signing',M('9999000918'),'Metrograph · Genevieve Yue and Erika Balsom.'],
['OCT 3 · 4:45 PM','Sympathy for Mr. Vengeance — LEENALCHI + Jang Young Gyu',L.sympathy,'Metrograph · composer Q&A moderated by Goran Topalovic.'],
['OCT 4 · 6:00 PM','The Edges of Cinema — free NYFF Currents talk','https://www.filmlinc.org/nyff2026/events/talk-the-edges-of-cinema/','Erika Balsom, Peggy Ahwesh, Éric Baudelaire and Tiffany Sia; tickets one hour before.'],
['OCT 4 · 8:45 PM; OCT 5 · 5:00 PM','Fjord — Cristian Mungiu & Sebastian Stan Q&As',L.fjord,'Buy at official price if available; otherwise wait for Oct 9.'],
['OCT 6 · 6:15 & 8:15 PM','Fjord — Mungiu and Stan IFC preview events',L.fjord,'Both sold out; monitor official returns only.'],
['OCT 8 · 7:30 PM','Vika Kirchenbauer Program 1',L.anthology,'Anthology · check official availability.'],
['OCT 15','La Bola Negra — Javier Calvo & Javier Ambrossi Q&A','https://www.paristheaternyc.com/event/la-bola-negra-paris-oct-15','Paris Theater · tickets live.'],
['OCT 16','The Devils — 35mm opening day',L.devils,'Film at Lincoln Center · tickets live.'],
['OCT 23','Possible Love — NYC theatrical opening','https://www.filmlinc.org/nyff2026/films/possible-love/','NYFF Q&A completed; revisit only if desired.']];
export default function Home(){return <main>
<header className="mast"><a className="brand" href="#top"><span className="brand-reel">●</span> NYC / ARTHOUSE <span className="brand-film">35MM</span></a><nav aria-label="Primary navigation"><a href="#picks">This Week</a><a href="#alerts">Tickets</a><a href="#nyff">NYFF64</a><a href="#special">Special Focus</a><a href="#asian">Asian</a><a href="#festival">Festival</a><a href="#all-other">All Other</a><a href="#soon">Coming Soon</a><a href="#events">Events</a><a href="#archive">Archive</a></nav></header>
<section className="hero" id="top"><div className="hero-rotator" aria-hidden="true"><span style={{backgroundImage:'url("'+I.overt+'")'}}/><span style={{backgroundImage:'url("'+I.sandwich+'")'}}/><span style={{backgroundImage:'url("'+I.fjord+'")'}}/></div><div className="hero-shade"/><div className="eyebrow hero-content"><span>✦ WEEK 09</span><span>NOW SHOWING · NEW YORK</span></div><div className="hero-title-wrap hero-content"><span className="projector-mark">◉</span><h1>NYC Arthouse<br/><em>Film Guide</em></h1><span className="film-strip">▯ ▯ ▯ ▯ ▯ ▯</span></div><div className="hero-foot hero-content"><p className="range">OCT 2 → OCT 8 <sup>2026</sup></p><p className="dek">NYFF64’s strongest remaining personal matches meet an unusually dense Taiwan New Cinema week.</p></div></section>
<section className="three"><div><p className="kicker">🎟 IF I COULD ONLY SEE THREE</p></div><ol><li><b>OVERT LISTENING</b><span>Tiffany Sia · world premiere Q&A</span></li><li><b>THE SANDWICH MAN</b><span>Hou · rare Taiwan New Cinema</span></li><li><b>FJORD</b><span>Mungiu + Sebastian Stan Q&A</span></li></ol></section>
<section className="section" id="picks"><div className="section-head"><p className="kicker">🎬 THIS WEEK</p><h2>Top picks</h2><p>Completed NYFF Q&As are removed from scarce slots; remaining discoveries, direct-focus repertory and appearances lead.</p></div><div className="pick-list">{picks.map((p,i)=><article className="pick image-pick" style={bg(p.image)} key={p.title}><div className="rank">{String(i+1).padStart(2,'0')}</div><div className="pick-main"><div className="tags">{p.tags.map(t=><Tag key={t}>{t}</Tag>)}</div><h3>{p.title}</h3><p>{p.text}</p></div><div className="showtime"><b>{p.when}</b><span>{p.venue}</span><a href={p.href} target="_blank" rel="noreferrer">Official listing ↗</a></div></article>)}</div></section>
<section className="mubi-band image-band" style={bg(I.concrete)}><div><p className="kicker">🎫 MUBI GO THIS WEEK</p><h2>Friday activation not yet public</h2></div><div className="mubi-copy"><p><b>Expected eligibility: Fri Oct 2–Thu Oct 8</b></p><p>The live U.S. GO payload still ended with Sep 25’s <em>The Scout</em> and did not expose an Oct 2 pick. Do not carry that expired pick forward or substitute a MUBI release.</p><p><b>Ticket call:</b> confirm title, theater and showtime in the app before redeeming.</p><a className="arrow" href={L.mubi} target="_blank" rel="noreferrer">Live MUBI GO offer ↗</a></div></section>
<section className="section ruled" id="alerts"><div className="section-head"><p className="kicker">🎟 PRIORITY TICKET ALERTS</p><h2>Act only where the event is irreplaceable</h2></div><div className="mini-grid"><article><Tag>KEEP / ATTEND</Tag><h3><a href={L.overt} target="_blank" rel="noreferrer">Overt Listening + Tiffany Sia</a></h3><p>Sat Oct 3 · noon. Keep the held ticket; skip the 1:30 PM Hamaguchi lecture conflict.</p></article><article><Tag>BUY AT FACE VALUE</Tag><h3><a href={L.fjord} target="_blank" rel="noreferrer">Fjord + Mungiu & Sebastian Stan</a></h3><p>Oct 4 · 8:45 PM or Oct 5 · 5:00 PM. Otherwise wait for the Oct 9 run.</p></article><article><Tag>MONITOR OFFICIAL RETURNS</Tag><h3><a href={L.fjord} target="_blank" rel="noreferrer">Fjord IFC previews</a></h3><p>Oct 6 · 6:15 and 8:15 PM are sold out. No resale premium.</p></article></div></section>
<section className="section dark" id="nyff"><div className="section-head"><p className="kicker">🎟 NYFF64 — WHAT TO PRIORITIZE</p><h2>The remaining personal map</h2><p>Possible Love and All of a Sudden Q&As are completed.</p></div><div className="mini-grid"><article><Tag>MUST SEE / BUY EARLY</Tag><h3>Overt Listening Q&A · Fjord Q&A</h3><p>Best combination of scarcity, guest value and personal fit.</p></article><article><Tag>FESTIVAL-EXPERIENCE PRIORITY</Tag><h3>The Day She Returns · Nowhere to Lay My Eyes · Everytime</h3><p>Protect one Hong experience; Everytime is flexible.</p></article><article><Tag>Q&A UPGRADE</Tag><h3>Fatherland</h3><p>Keep the cheaper FLC Q&A already secured; skip standard BAM.</p></article><article><Tag>CAN WAIT</Tag><h3>NAZA · Rose · Fjord standard</h3><p>NAZA is at IFC; Fjord opens Oct 9.</p></article><article><Tag>COMPLETED / LOWER PRIORITY</Tag><h3>Possible Love · All of a Sudden · Bucking Fastard · Heil Jupiter!</h3><p>Do not replace sold tickets or repeat what did not work.</p></article></div></section>
{[['special','01 / 🎯 SPECIAL FOCUS','Hou, Tsai, Edward Yang and Hong Sangsoo',focus],['asian','02 / 🌏 ASIAN CINEMA','Taiwan, Korea and Japan',asian],['festival','🏆 FESTIVAL','Cannes, Berlinale and Locarno selections',festival],['classics','04 / 🎞 ALL-TIME CLASSICS','Canon in presentations that matter',classics],['new','05 / 🆕 NEW HITS','Current independent openings',newHits],['worth','06 / ⭐ WORTH SEEING','Guest-bearing alternatives',worth],['noteworthy','07 / 🎥 OTHER NOTEWORTHY SCREENINGS','Formal risk, rare prints and underground history',noteworthy]].map((s,i)=><section className={'section '+(i%2===0?'dark':'')} id={s[0] as string} key={s[0] as string}><div className="section-head"><p className="kicker">{s[1] as string}</p><h2>{s[2] as string}</h2>{s[0]==='special'&&<p>No confirmed NYC event for Nuri Bilge Ceylan, Lynch, Tarkovsky, Kore-eda, Jia, Kiarostami, Panahi or Apichatpong emerged in the 90-day official watch.</p>}</div><div className="card-grid">{(s[3] as Film[]).map((f,j)=><Card key={f.title+j} f={f}/>)}</div></section>)}
<section className="section schedule dark" id="all-other"><div className="section-head"><p className="kicker">08 / 📋 ALL OTHER SCREENINGS</p><h2>The rest of the seven-day map</h2><p>Additional worthwhile screenings from the full venue sweep; featured films excluded.</p></div><div className="schedule-grid">
<div><h3>FRI OCT 2</h3><p>Metrograph — Tokyo Melody <TL href={M('9999005006')}>2:15 PM</TL>; Oedipus Rex <TL href={M('9999002042')}>3:45 PM</TL>; RoboCop director’s cut <TL href={M('9999000720')}>3:50 PM</TL>; Daughter’s Daughter <TL href={M('9999004567')}>5:50 PM</TL>; O Brother 35mm <TL href={M('9999005017')}>6:00 PM</TL>; Train to Busan <TL href={M('9999003912')}>10:25 PM</TL>; Alien: Resurrection 35mm <TL href={M('9999001729')}>10:30 PM</TL>. MoMA — Once Upon a Time in China <TL href={L.moma}>4:00 PM</TL>; The Grandmaster (Hong Kong cut) <TL href={L.moma}>7:00 PM</TL>. BAM NYFF — My Wife Cries <TL href={L.bamNyff}>4:15 PM</TL>; Foreign Travel <TL href={L.bamNyff}>6:30 PM</TL>; Joy of Joys <TL href={L.bamNyff}>8:15 PM</TL>.</p></div>
<div><h3>SAT OCT 3</h3><p>Metrograph — Pushing Hands <TL href={M('9999005009')}>noon</TL>; Amour 4K <TL href={M('9999001734')}>2:15 PM</TL>; Pelham 35mm + intro/book signing <TL href={M('9999000918')}>2:30 PM</TL>; Invisible Adversaries + Lynne Sachs <TL href={M('9999005019')}>4:45 PM</TL>; The Wailing + Jang Young Gyu <TL href={M('9999003989')}>7:50 PM</TL>; Electra, My Love <TL href={M('9999002564')}>9:15 PM</TL>; Heathers <TL href={M('9999003369')}>11:00 PM</TL>. MoMI — Creature from the Black Lagoon 3-D <TL href="https://movingimage.org/event/the-creature-from-the-black-lagoon-in-3-d/">1:00 PM</TL>. IFC — Angel’s Egg <TL href="https://www.ifccenter.com/films/angels-egg/">11:50 PM</TL>.</p></div>
<div><h3>SUN OCT 4</h3><p>Metrograph — Small Change 35mm <TL href={M('9999001550')}>11:00 AM</TL>; Amour 4K <TL href={M('9999001734')}>1:00 PM</TL>; High and Low 35mm <TL href={M('9999000181')}>1:15 PM</TL>; The Practice of Love <TL href={M('9999005020')}>3:30 PM</TL>; Nostos <TL href={M('9999005021')}>4:10 PM</TL>; Valie Export shorts + Joan Jonas <TL href={M('9999005022')}>5:25 PM</TL>; The Yellow Sea <TL href={M('9999005014')}>6:45 PM</TL>. IFC — No Skin Off My Ass + Bruce LaBruce <TL href="https://www.ifccenter.com/films/no-skin-off-my-ass/">6:00 PM</TL>; Super 8½ <TL href="https://www.ifccenter.com/films/super-8-1-2/">8:15 PM</TL>. MoMI NYFF — Rose <TL href={L.bamNyff}>3:45 PM</TL>.</p></div>
<div><h3>MON OCT 5</h3><p>Metrograph — Pushing Hands <TL href={M('9999005009')}>3:50 PM</TL>; Women on the Verge 35mm <TL href={M('9999003126')}>4:00 PM</TL>; The Wedding Banquet 35mm <TL href={M('9999000475')}>6:00 PM</TL>; Medea <TL href={M('9999002034')}>8:10 PM</TL>; Morvern Callar 35mm <TL href={M('9999005063')}>8:15 PM</TL>. IFC — Hereditary × Monstrous Bitch <TL href="https://www.ifccenter.com/films/hereditary-x-monstrous-bitch/">6:30 PM</TL>. BAM NYFF — Club Kid <TL href={L.bamNyff}>6:00 PM</TL>; What Can’t Be Mentioned + Q&A <TL href={L.bamNyff}>8:45 PM</TL>.</p></div>
<div><h3>TUE OCT 6</h3><p>Metrograph — Iphigenia 16mm <TL href={M('9999005005')}>4:20 PM</TL>; Se7en 35mm <TL href={M('9999005000')}>7:00 PM</TL>; Time and Tide 35mm <TL href={M('9999003587')}>9:45 PM</TL>. Anthology — Laboring Images <TL href={L.anthology}>6:30 PM</TL>; Sicilia! <TL href={L.anthology}>8:15 PM</TL>. BAM NYFF — Fatherland <TL href={L.fatherland}>6:00 PM</TL>; Dao <TL href={L.bamNyff}>8:15 PM</TL>. Bronx NYFF — Bucking Fastard <TL href={L.bamNyff}>6:00 PM</TL>.</p></div>
<div><h3>WED OCT 7</h3><p>Metrograph — O Brother 35mm <TL href={M('9999005017')}>3:45 PM</TL>; Treasure of Bitch Islands 4K <TL href={M('9999001726')}>5:40 PM</TL>; Ninth Gate 35mm <TL href={M('9999005003')}>7:50 PM</TL>; Ghost in the Shell 4K <TL href={M('9999000710')}>10:30 PM</TL>; Warriors 35mm <TL href={M('9999002970')}>10:35 PM</TL>. Anthology — Secret Life of AFA <TL href={L.anthology}>7:30 PM</TL>; Seduction: The Cruel Woman <TL href={L.anthology}>9:00 PM</TL>. BAM NYFF — Nitrate Kisses <TL href={L.bamNyff}>6:00 PM</TL>; Clarissa <TL href={L.bamNyff}>7:45 PM</TL>.</p></div>
<div><h3>THU OCT 8</h3><p>Metrograph — Alien: Resurrection 35mm <TL href={M('9999001729')}>2:00 PM</TL>; Chungking Express <TL href={M('9999000735')}>2:10 PM</TL>; Sakamoto | Opus <TL href={M('9999005011')}>4:15 PM</TL>; Peking Opera Blues 4K <TL href={M('9999004982')}>6:20 PM</TL>; Valie Export shorts <TL href={M('9999005022')}>8:30 PM</TL>; Ghost in the Shell 4K <TL href={M('9999000710')}>10:00 PM</TL>. IFC — Altered States <TL href="https://www.ifccenter.com/films/altered-states/">4:05 PM</TL>; Whore <TL href="https://www.ifccenter.com/films/whore/">1:55 PM</TL>; V/H/S/Mixtape <TL href="https://www.ifccenter.com/films/v-h-s-mixtape/">9:30 PM</TL>. BAM NYFF — Double Freedom <TL href={L.bamNyff}>6:00 PM</TL>; Dreamed Adventure <TL href={L.bamNyff}>8:15 PM</TL>.</p></div>
</div></section>
<section className="section soon" id="soon"><div className="section-head"><p className="kicker">09 / 🔭 COMING SOON — SPECIAL FOCUS</p><h2>Direct matches and 90-day watch</h2></div><div className="card-grid"><Card f={{title:'All of a Sudden / Soudain',year:'2026',region:'France / Japan / Germany / Belgium',director:'Ryūsuke Hamaguchi',type:'Drama',venue:'NYC venue to confirm',when:'Nov 18–19 previews; opens Nov 25',tags:['SPECIAL FOCUS','REWATCH OPTION'],text:'The NYFF Q&A was completed and deeply enjoyed. Treat November as an intentional rewatch, not scarcity; confirm venue and time.',href:'https://www.filmlinc.org/nyff2026/films/all-of-a-sudden/',image:'https://wp.filmlinc.org/wp-content/uploads/2026/07/All-of-a-Sudden_NYFF64_02.jpeg'}}/><Card f={{title:'Possible Love / 가능한 사랑',year:'2026',region:'South Korea',director:'Lee Chang-dong',type:'Drama',venue:'FLC / select theaters',when:'Opens Oct 23; Netflix Nov 6',tags:['SPECIAL FOCUS','THEATRICAL OPENING'],text:'The NYFF premiere and Q&A are completed. This is a low-pressure revisit; no premium warranted.',href:'https://www.filmlinc.org/nyff2026/films/possible-love/',image:'https://wp.filmlinc.org/wp-content/uploads/2026/07/Possible-Love_NYFF64_01.jpeg'}}/></div></section>
<section className="section soon dark" id="new-releases"><div className="section-head"><p className="kicker">10 / 🔭 COMING SOON — NEW RELEASES</p><h2>Openings in the next 30 days</h2></div><div className="card-grid"><Card f={{...fjord,venue:'IFC Center',when:'Opens Fri Oct 9',event:undefined,tags:['NEON','PALME D’OR','NYC OPENING'],text:'The IFC run is the cost-efficient fallback.'}}/><Card f={{title:'All About Lily Chou-Chou',year:'2001',region:'Japan',director:'Shunji Iwai',type:'Youth drama',venue:'IFC Center',when:'Opens Fri Oct 9',tags:['ASIAN CINEMA','CULT CANON'],text:'Iwai’s digital-age adolescent dreamscape returns theatrically. Abundant dates mean no opening-night rush.',href:L.lily,image:I.lily}}/><Card f={{title:'The Devils',year:'1971',region:'UK',director:'Ken Russell',type:'Historical horror',venue:'FLC / IFC',when:'FLC opens Oct 16 on 35mm; IFC Oct 15',format:'35mm at FLC',tags:['35MM','TRANSGRESSIVE CANON'],text:'The month’s major cult-canon return. Favor FLC’s 35mm presentation.',href:L.devils,image:I.devils}}/></div></section>
<section className="section events" id="events"><div className="section-head"><p className="kicker">11 / 🎤 NYC FILM EVENTS</p><h2>30-day event radar</h2></div><div className="event-list">{events.map(e=><div key={e[0]+e[1]}><time>{e[0]}</time><h3><a href={e[2]} target="_blank" rel="noreferrer">{e[1]}</a></h3><p>{e[3]}</p></div>)}</div></section>
<section className="section" id="calendar"><div className="section-head"><p className="kicker">📅 30-DAY EVENT CALENDAR</p><h2>At a glance</h2></div><div className="mini-grid"><article><Tag>OCT 2–5</Tag><h3>Guest-heavy weekend</h3><p>Sia, Mungiu, Stan, LaBruce, Jang, Yue and Balsom.</p></article><article><Tag>OCT 6–12</Tag><h3>NYFF closing stretch</h3><p>Hong priorities, borough shows and sold-out Fjord previews.</p></article><article><Tag>OCT 15–31</Tag><h3>Opening watch</h3><p>La Bola Negra Q&A, The Devils 35mm, Possible Love, Fatherland and Claire Atherton.</p></article></div></section>
<section className="section" id="archive"><div className="section-head"><p className="kicker">🗃 PREVIOUS WEEKS / ARCHIVE</p><h2>Rolling 10-week archive</h2></div><div className="mini-grid">{[['08','Sep 25–Oct 1','Possible Love, Goodbye Dragon Inn and Sakamoto.'],['07','Sep 18–24','The Assassin, The World and Stray Dogs.'],['06','Sep 11–17','Dust in the Wind, Rebels and A Brighter Summer Day.'],['05','Sep 4–10','Daughter of the Nile, Solaris and A Brighter Summer Day.'],['04','Aug 28–Sep 3','Goodbye, Dragon Inn, Nostalghia and Mulholland Drive.'],['03','Aug 21–27','Memoria, Happy Hour and Stalker.'],['02','Aug 14–20','Ōshima, Irréversible, 2001 and Ozu.'],['01','Aug 8–14','The Hole, Late Fame, Millennium Mambo and Center Stage.']].map(a=><article key={a[0]}><Tag>WEEK {a[0]}</Tag><h3>{a[1]}, 2026</h3><p>{a[2]}</p><a href={'/chrisfilmguide/archive/week-'+a[0]+'/'}>Open archived edition ↗</a></article>)}</div></section>
<footer><p><b>IF I COULD ONLY SEE THREE:</b> Overt Listening · The Sandwich Man · Fjord</p><p>Verified against official listings on Oct 2, 2026. Recheck live ticket inventory before travel.</p></footer>
</main>}
